### ISSUE TITLE
Parsing of csv file fails

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#103]
I am not able to parse this file

https://www.dropbox.com/s/9q4z0kup4wkj3cb/metadata.csv.gz?dl=0

even with conservative options to have everything string and exclude the "long text" columns.

```
 (ds/->dataset "metadata.csv.gz" {:column-blacklist ["abstract" "title"] :parser-fn :string  :parser-scan-len 200000}))
```

I get 
```
Execution error at tech.ml.dataset.parse$simple_string_parser$reify__50627/simple_parse_BANG_ (parse.clj:260).
Text data not string data
```

I can parse it with R dplyr::read_csv without problems, and it opens in localc as well.

```
readr::read_csv("./metadata.csv.gz",col_types="ccccccccccccccccccc")

```

**Comment by behrica** [comment]
I figured it out.

I need to use :parser-fn :text instead of :parser-fn :string

**Comment by cnuernber** [comment]
That works as a workaround but that file should parse out of the gates.  I think this is still a valid issue personally :-).  Definitely wil look at this when I address issue #102
