### ISSUE TITLE
"abstract" column name is hardcoded in path-token-map->bag-of-words

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#106]
https://github.com/techascent/tech.ml.dataset/blob/f57fe86741fd0c0158a643c946404b78bd09c90a/src/tech/ml/dataset/text/bag_of_words.clj#L68

I think you want to refer to variable "bag-of-words-colname"

**Comment by cnuernber** [comment]
Yep, sorry, will change presently

**Comment by cnuernber** [comment]
Fixed in `2.12`
