### ISSUE TITLE
investigate string compression for large strings

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#107]
I did one benchmark to see how many bytes normal strings versus compressed strings require using a sring compression library:

https://github.com/lithedream/lithestring

On english medical tests with a sample of 1000000 texts,
I save roughly 50 % of bytes:

1 GB vs 0.5 GB

Quite something, I would say.

It's definite much slower, to be measured.
Probably far worse on write then on read.

```
(def some-strings
    (doall
     (remove empty?
             (take 1000000
                   (seq abstracts)))))

  (reduce + 
          (map #(count (.getBytes %)) some-strings))
  ;; => 990 234 252 

  (reduce + 
          (map #(count (LitheString/zip %)) some-strings))
;; => 502 777 200  

```

**Comment by behrica** [comment]
We can close this.

Even though it does work, so reducing the memory consumption to 60 % is realistic, it is too slow.

Reading and compressing 8 GB of 8 000 000 "smallish" texts takes around 30 minutes (vs 3 minutes without compression)

**Comment by cnuernber** [comment]
Sounds good to me.
