### ISSUE TITLE
allow reading a CSV file from a given starting row

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#109]
This would allow to handle large files in blocks "starting row" -> "num rows"

see here for background:  https://github.com/techascent/tech.ml.dataset/issues/102#issuecomment-654217886

**Comment by cnuernber** [comment]
How would you deal with the header row in this case?  Using the univocity argument for this unfortunately drops the head row so this could be implemented with a `drop n` pathway on top of csv->rows that was header-row aware.

**Comment by behrica** [comment]
Is this maybe already implemented ?

https://github.com/techascent/tech.ml.dataset/blob/f0b039105f174623eaa13c3704763d4afd0c898d/src/tech/ml/dataset/parse.clj#L775

I see the n-skip-initial-rows parameter -

**Comment by cnuernber** [comment]
That drops the header rows which could present problems to people.  But it does work efficiently.

**Comment by cnuernber** [comment]
Closing this for now.  It is possible and the side effect is you have to sometimes rename the columns.  But it works with files that really are noisy.
