### ISSUE TITLE
add a way to sample rows from a CSV file

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#110]
see here: https://github.com/techascent/tech.ml.dataset/issues/102#issuecomment-654217886

**Comment by cnuernber** [comment]
The way to do this is very similar to loading a csv into a sequence of datasets:

https://github.com/techascent/tech.ml.dataset/commit/52ce1953baa6e287ec1d4dfaf656946fcaf59ff8

**Comment by cnuernber** [comment]
I made a quick attempt to do this so perhaps we are there:
https://techascent.github.io/tech.ml.dataset/tech.v3.dataset.io.string-row-parser.html
