### ISSUE TITLE
add progress report to reading of data

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#111]
Reading large data files can take up to several minutes.

We should have a way to "show progress".

Maybe the most flexible is to allow the user to specify a call back function

progres [index total]

which is called with current row and the total (if known).

**Comment by cnuernber** [comment]
We won't generally know the number of rows of a file, but we can know the number of bytes read and the length of a file if the input source is in fact a file.

For things that aren't files (like streams from http) then we won't know the length of the file so then we would only know the bytes read.

**Comment by behrica** [comment]
Yes, for certain sources it cannot be known.

For large files I even typically check myself with "wc -l" before, so I know how long a simple line counting progress should take.

So maybe we should have a more general callback, like

(progress [line-current line-total bytes-current bytes-total] 

and it is documented that all four could be nil, dependent on data source

**Comment by behrica** [comment]
> Yes, for certain sources it cannot be known.
> 
> For large files I even typically check myself with "wc -l" before, so I know how long a simple line counting progress should take.
> 
> So maybe we should have a more general callback, like
Probably byte counting only is enough as well.

**Comment by cnuernber** [comment]
Closing with wontfix as I am not going to work on this an no one else is submitting PR's or commenting on this issue.
