### ISSUE TITLE
columns don't implement hasheq

### ISSUE THREAD

**Issue by joinr** [techascent/tech.ml.dataset#114]
```clojure
techjoin.check> (hash (tech.ml.dataset.column/new-column "Column-1" (range 10)))
273865333
techjoin.check> (hash (tech.ml.dataset.column/new-column "Column-1" (range 10)))
1906613126
techjoin.check> (hash-ordered-coll (tech.ml.dataset.column/new-column "Column-1" (range 10)))
804834377
techjoin.check> (hash-ordered-coll (tech.ml.dataset.column/new-column "Column-1" (range 10)))
804834377
```

More equality rabbit hole stuff, but seemingly easy to patch.  Contributes toward hasheq for datasets, leading to false failures for equality checks (discovered through  #113 )

**Comment by cnuernber** [comment]
Relevant to this issue:
https://github.com/techascent/tech.datatype/blob/master/src/tech/v2/datatype.clj#L687

Use the column's default reader and use this method to create a persistent vector out of it.  I guess then you have to cache the hashcode and all that also.

**Comment by joinr** [comment]
Oh, that's much better than the hack I looked at the worked (from the dataset side) is to just compute the hashes manually, ala

```clojure
techjoin.check> (hash-unordered-coll (map (fn [[k v]] (hash [k (hash-ordered-coll v)]))  r))
-255751347
techjoin.check> (hash-unordered-coll (map (fn [[k v]] (hash [k (hash-ordered-coll v)]))  l))
-255751347
```

Is there any objection to me implementing hashEq on column by caching _hash and _hasheq (as we did with dataset) using .hashCode and .hashEq results from `reader-as-persistent-vector` in tech.ml.dataset.column?

I'm assuming they are not mutable, and that persistent vector semantics are fine (at least the default column).  If this isn't true, then caching the hashes would be invalid.

**Comment by cnuernber** [comment]
No objection at all.

**Comment by joinr** [comment]
It looks like ListPersistentVector. is just a wrapper deriving from APersistentVector, so maybe just cache the ListPersistentVector as needed, and delegate hashCode/hashEq to the cached vector? I don't think this would cause any leaks or other nastiness, and would make the implementation very simple (e.g. another mutable field to cache, but the equality semantics are shared with vector).  How does that sound?

**Comment by cnuernber** [comment]
That seems like the minimal cost pathway.  The reader I believe is a public variable on the list persistent vector so you could even use it as the cached reader impl and just get the reader from the member variable when requested.

**Comment by joinr** [comment]
You mean the existing "generic-reader" field that I put in?  We could just delegate everything to the lpv.  Looks like it only matters for nth, invoke, and iterator.  That would be a more parsimonious path, with the same performance.

**Comment by cnuernber** [comment]
Good point, yep, that would also work I think.  There may be cases where it is better to return the actual reader but I can't think of any offhand.

**Comment by joinr** [comment]
Does it make sense to have a `cons` implementation?  Looking at getting `equiv` in , but that comes from IPersistentCollection, so there would either be a stub for `cons` with a not-implemented exception, or it'd be allowed, but would open up some decisions...like if you do allow .cons/conj on columns, then do you respect the underyling datatype and promote if the element being conj'd is not reconciled (e.g. conjing a long onto a int, or a string onto a long column would require promoting or widening the type necessarily).  The other path would be to automatically promote to an object column, which IMO is undesirable since that opens back up the slow path and storage concerns that drove the column implementation.

I don't see any means in the column API in tech.ml.dataset.column, so I'm going to assume that the default would be to stub out the cons method with an exception for now....

Beyond that, I think everything works out nicely.  Most operations just delegate to the vector, so all the readable properties of a vector and hashing are inherited by the column (for what little that's work in practice, but who knows).

**Comment by cnuernber** [comment]
I don't think a const implementation makes sense both due to the reasons you suggest here and because I don't see how to support it with with the underlying reader implementation.  

Yes, nice work, this looks like a nice bit of progress.

**Comment by joinr** [comment]
Very interesting.  Going down the path without the explicitly cached reader, I'm seeing lookup times for `nth` at like 1.5-2x higher than compared to a similar lookup on a vector of the same values (actually just a vector created from the column).  Still very fast compared to the early transition to efficient `nth`, but substantially slower than I expected (this should be more or less a free op).

I profiled a similar case with the object reader, replicating caching checks from the earlier `generic-reader`, and it's right down with vector lookup performance...

[repl profiling output](https://github.com/techascent/tech.ml.dataset/files/4905229/repl.clj.txt)

[current patch](https://github.com/techascent/tech.ml.dataset/files/4905227/patch.diff.txt)

Will explore why there's a hit to `nth` performance this way, and if it can't be solved, lift out the generic reader as before
and leverage that for fastest possible lookups, leverage the ListPersistentVector for everything else.

**Comment by joinr** [comment]
Good news is collection-check is working now, except for metadata comparisons.

**Comment by cnuernber** [comment]
This looks like it also fixes the npe issues with empty datasets.
