### ISSUE TITLE
Vega vis label thoughts

### ISSUE THREAD

**Issue by harold** [techascent/tech.ml.dataset#12]
I'd like to be able to add a label to both a plot:
![image](https://user-images.githubusercontent.com/7443/71835367-97d3d700-306e-11ea-84e5-f10ad3c509cd.png)

And individual axes:
![image](https://user-images.githubusercontent.com/7443/71835391-acb06a80-306e-11ea-9c28-58139aca4b55.png)

**Comment by cnuernber** [comment]
This is half-implemented in tech.viz :-).
