### ISSUE TITLE
readme incorrect since 3.x change

### ISSUE THREAD

**Issue by joinr** [techascent/tech.ml.dataset#120]
I noticed the readme example for using `meta` was incorrect after the change to 3.x.  I re-ran the examples in the repl and copied the output for consistency (notably, the default dataset label now is the URL the data was drawn from).  Default column names are now `column-0` instead of `0`.

Added examples for using `assoc`, `dissoc`, destructuring.

[patch.diff](https://github.com/techascent/tech.ml.dataset/files/4922040/patch.diff.txt)

**Comment by harold** [comment]
👍 - so cool to have some of your efforts, @joinr --- Just wanted to say I've been having fun w/ destructuring and writing some terse stuff with `assoc` over `add-column` and such.

Stay rad.

**Comment by joinr** [comment]
Glad to hear there's a bit of quality of life improvement (or perhaps a smaller surface area for the novel API stuff).
