### ISSUE TITLE
Final tweak of readme

### ISSUE THREAD

**Issue by joinr** [techascent/tech.ml.dataset#121]
Sorry, I unintentionally overlooked the legacy claim:

"Datasets are sequence of columns."

This is now removed.

In the process, I added a bit more prose on the composition of datasets, and common access patterns.
Minor prose changes.

[patch.diff](https://github.com/techascent/tech.ml.dataset/files/4925920/patch.diff.txt)

**Comment by cnuernber** [comment]
Thanks a ton, applied :-).
