### ISSUE TITLE
custom separator in csv causes exception

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#123]
I have csv file separated by semicolon `;` and I'm getting ClassCastException when trying to set custom separator.
The minimal example is a file containing only one digit (eg. 1)

```sh
$ cat r.csv 
1
```

```clojure
(tech.ml.dataset/->dataset "r.csv" {:header-row? false})
;; => r.csv [1 1]:
;;    | column-0 |
;;    |----------|
;;    |        1 |

(tech.ml.dataset/->dataset "r.csv" {:header-row? false
                                    :separator ";"})
;; EXCEPTION
```

**Comment by joinr** [comment]
@genmeblog  Looks like expectation is that separator is a char (could be inferred from single-length string, should be IMO):

```clojure
user> (ds/->dataset "r.csv" {:header-row? false :separator \;})
r.csv [1 1]:

| column-0 |
|----------|
|        1 |
```

**Comment by genmeblog** [comment]
Oh. It's even stated in the docs... I agree that in case of providing string it can be inferred.
