### ISSUE TITLE
select-rows allows to mark selection outside range

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#124]
Following code works. Of course trying to print or manipulate column `:a` throws an exception. I think it should be protected during row selection.

```clojure
(let [ds (-> (tech.ml.dataset/->dataset [{:a 1} {:a 3}])
             (tech.ml.dataset/select-rows (range 100)))]
  (tech.ml.dataset/row-count ds))
;; => 100
```

**Comment by joinr** [comment]
Looks like the reader is optimistic and not checking the input to see if [index space is valid](https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/ml/dataset/impl/column.clj#L344).

At some point down the line, the indexed reader will throw an exception as it tries to read values beyond [0 1], but this should happen early with bounds checking.  If you do this eagerly for every operation, one potential downside is that you need to traverse the indices (every time a selection is made) to compute the max and check bounds, for every column.

**Comment by joinr** [comment]
Maybe you only need to do bounds check once, since columns will have the same length.

**Comment by joinr** [comment]
@genmeblog  Is the expected behavior to throw an error, or to select the intersection of actual rows with the requested range?  Are the indexes concrete bounds or a filtering predicate?

**Comment by joinr** [comment]
Another problem case this exposes:

```clojure
user> (let [ds (-> (tech.ml.dataset/->dataset [{:a 1} {:a 3}])
                   (tech.ml.dataset/select-rows (range -100 100)))]
        (tech.ml.dataset/row-count ds))
200
```

**Comment by genmeblog** [comment]
I think intersection is the best solution here.

**Comment by cnuernber** [comment]
Intersection makes sense.  For some datatypes, like ranges, I have implemented a protocol - has-constant-time-min-max? to allow that intersection to be constant time.  If the user passes in just arbitrary data that array of integers could be quite large and then I think you get just an error upon index.  But for things for which a constant time min/max are available then intersection works out well.

**Comment by cnuernber** [comment]
that was kind of tough.  Glad this came up :-).
