### ISSUE TITLE
Explicit support operating on big (parquet) data

### ISSUE THREAD

**Issue by cnuernber** [techascent/tech.ml.dataset#125]
Carsten Behring on zulip writes:

> The memory mapped access to arrow files on disk looks indeed very promising.
I was looking at it, and tried to figure out, how to use it on a concrete data analysis task, but could not really see it.

> I did not find a way to "transform" existing "Big data" (in parquet or csv file format) into the on-disk arrow format which seems to be required by the new arrow support in t.m.d 3.0.8

> I am as well confused between the "parquet", "arrow" and "feather" formats....

> I found a very interesting R example, what the arrow package for R allows to do:
https://cran.uni-muenster.de/web/packages/arrow/vignettes/dataset.html

> namely to work with 37 GB of parquet data on disk and run some queries in seconds on it.

> It it possible to replicate the same analysis with tech.ml.dataset 3.0.8 in similar performance ?
> If yes -> great, we are there.

> If not, what is missing ?

**Comment by behrica** [comment]
This relates to #128 

Parquet is definitely the big data file format which should be supported by t.m.d
If we could do a similar memory-mapping then I have tried for arrow files,
this would be amazing.

I am not sure, if t.m.d should natively support all three fromats "csv","arrow","parquet" or if we should rely on conversions

**Comment by cnuernber** [comment]
This is supported in a poor way by converting parquet files into arrow files and loading arrow files in-place.

A better way takes a bit of digging into the parquet format.

**Comment by behrica** [comment]
> This is supported in a poor way by converting parquet files into arrow files and loading arrow files in-place.
> 
In t.m.d or with outside tools ?
Cam t.m.d read large parquet files in batches and write to arrow ?

I would not mind too much if an initial step of each data analysis work with t.m.d and huge files would consist in converting them ones to arrow.

**Comment by cnuernber** [comment]
I think this is partially addressed in other ways.  I would definitely welcome a PR, however, that enables reading parquet file directories like in the benchmark.
