### ISSUE TITLE
"w" is invalid mode for random access file

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#127]
I got an Exception here,
using "rw" fixed it.

https://github.com/techascent/tech.ml.dataset/blob/d04a3d4cb1ea445cd427240bd5eb2b89a2352c8e/src/tech/libs/arrow/copying.clj#L642

Docu seems to say the same: https://docs.oracle.com/javase/7/docs/api/java/io/RandomAccessFile.html

**Comment by cnuernber** [comment]
Ah, interesting, I will change that.  I was unable to get the arrow file pathway working and since it is just the stream pathway with tags at the beginning and end I stopped.  For the simple stocks dataset the arrow file pathway failed to read back correctly.

**Comment by cnuernber** [comment]
Fixed before https://github.com/techascent/tech.ml.dataset/commit/52ce1953baa6e287ec1d4dfaf656946fcaf59ff8

**Comment by cnuernber** [comment]
I did remove that function from the public api but left it in the copying namespace so we can still work on it until it works.  What I don't have is reading pathways for file.  It is annoying that arrow in essence published 3 binary formats: stream, file, and feather.  For now, stream appears to be winning and file is really a small change from stream.  Feather seems to have died on the vine.
