### ISSUE TITLE
Vega viz design next thought

### ISSUE THREAD

**Issue by harold** [techascent/tech.ml.dataset#13]
Doing dataset -> vega is good and fun and has already proved very useful.

It occurs to me that there's nothing really dataset specific in the operations, however. I could imagine splitting the vega/viz portion out to work on (probably?) sequences of values, and then calling into that with thin wrappers that extract the sequences of values from datasets - to keep the code easy to use from `ds`.

The upside would be that if some data doesn't happen to be in a dataset, we could avoid the extra step of turning it into a dataset just for the purposes of vis.

**Comment by cnuernber** [comment]
What do you think about creating tech.viz for this to live in?  Agreed, while it is useful to be able to visualize aspects of datasets quickly the viz pathway isn't at all tied to datasets.  In this case, I think a generalization of a map of column name->column values gets you pretty far and that is still a lot more general than a dataset.  

Or are you thinking of a row-major datastore (such as a sequence of maps)?  

In any case, I think a new project, tech.viz, makes sense.

**Comment by harold** [comment]
> What do you think about creating tech.viz for this to live in?
>

Smart!

> I think a generalization of a map of column name->column values gets you pretty far and that is still a lot more general than a dataset.
>

This seems like a fine place to start. I can see how to map this on to at least the kinds of basic charts I want to start with.

> Or are you thinking of a row-major datastore (such as a sequence of maps)?
>

I wasn't really thinking in this direction - if the dataset pathway stays intact then going from seq-of-maps -> dataset -> viz is easy enough.

> In any case, I think a new project, tech.viz, makes sense.
>

Yup, then this project comes to depend on that one eventually.

**Comment by cnuernber** [comment]
Closing, this is moving to tech.viz.
