### ISSUE TITLE
make read-stream-dataset-inplace return a sequence of datasets per record batch

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#130]
For me it worked well with a simple change:

```clojure
@@ -320,8 +320,11 @@
         data-record (first rest-messages)
         _ (when-not (= :record-batch (:message-type data-record))
             (throw (Exception. "No data records detected")))]
-    (-> (records->ds schema dict-map data-record)
-        (ds-base/set-dataset-name fname))))
+    (map-indexed #(-> (records->ds schema dict-map %2)
+              (ds-base/set-dataset-name (str fname "@" %1))
+         rest-messages)))
+
+
```

**Comment by behrica** [comment]
This gives me all data as a sequence of data sets.

Then I can either ds/concat   (when #129 is fixed) 
or map over them

**Comment by cnuernber** [comment]
Added methods to write/read sequences of datasets in https://github.com/techascent/tech.ml.dataset/commit/5c99381e75cb4b2796386bd1d4a7b7d694ac674c.

Still need method to, given a csv, produce a sequence of datasets.

**Comment by cnuernber** [comment]
Done - https://github.com/techascent/tech.ml.dataset/commit/52ce1953baa6e287ec1d4dfaf656946fcaf59ff8
