### ISSUE TITLE
general feedback support on long operations

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#134]
As t.d.m gets now ready for big data,
I think we should think about "some form" of feedback on long running operations.

I have no idea, on how this could be implemented (with a optional callback ?) on "all operations"....

Specially operating on the memory mapped files will result in operation times of minutes easily.
In principle, this is fine, specially because I will most of the time work with subset of data,

But I would like to know quickly, if an operation is expected to run for minutes (fine, so I go for a coffee)  or "hours" ... (so probably I want to press control-c.... and think about what I do)

i have no the big "hope", that with mmaped files, control-c will work well.
Which does not, if GC pressure is high due to a "unwanted long operation".

Somehow all operations operate on "rows" in a certain way, correct ?
So "going over rows" is a kind of progress, which could be shown (or notified)

A working "control-c" in the repl on too long operations (which is out of scope to make it work for t.d.m, in case it does not work yet) and some form of progress report on long operation, would somehow be the last missing piece to bring the good experience of "working with largish data" which I have in R into clojure / JVM.

**Comment by behrica** [comment]
The idea of a callback probably does not make sense...
Even something like (last ds) can take very long on mmaped files
Maybe some form of optional logging or similar

**Comment by behrica** [comment]
Lazyness of clojure makes it as well complicated....

**Comment by cnuernber** [comment]
A PR here would be welcome.  Outside of that I am not going to spend time fixing this.
