### ISSUE TITLE
one-hot fails if column names are strings

### ISSUE THREAD

**Issue by alex314159** [techascent/tech.ml.dataset#140]
Hi Chris,

Thanks again for this great library. Compare the following:

`(def ktable (ds/->dataset [{:a 1 :b "AA"} {:a 2 :b "AA"} {:a 3 :b "BB"} {:a 4 :b "BB"}]))`
`(def table (ds/->dataset [{"a" 1 "b" "AA"} {"a" 2 "b" "AA"} {"a" 3 "b" "BB"} {"a" 4 "b" "BB"}]))`

`(ds-pipe/one-hot ktable)`
=> _unnamed [4 3]:

| :a | :b-BB | :b-AA |
|----|-------|-------|
|  1 |   0.0 |   1.0 |
|  2 |   0.0 |   1.0 |
|  3 |   1.0 |   0.0 |
|  4 |   1.0 |   0.0 |

`(ds-pipe/one-hot table)`
=> _unnamed [4 2]:

| a |   b |
|---|-----|
| 1 | 1.0 |
| 2 | 1.0 |
| 3 | 1.0 |
| 4 | 1.0 |

This is confusing behaviour - is that expected / should there be guidelines on when not to use strings as column headers?

**Comment by cnuernber** [comment]
No, this should work and is an issue.  You are using it correctly for sure.
