### ISSUE TITLE
ds/select keeps memory of original dataset?

### ISSUE THREAD

**Issue by alex314159** [techascent/tech.ml.dataset#141]
Hi Chris,

hope you are well, some strange behaviour with ds/select, looks like it's keeping a view internally instead of creating a new object but can be confusing - I would have expected the following to error out:

```
(def original (ds/->dataset [{:a 0} {:a 1} {:a 2} {:a 3} {:a 4}]))
=> #'jasmine.svm/original
(def new (ds/select-rows original (range 0 4)))
=> #'jasmine.svm/new
new
=> _unnamed [4 1]:

| :a |
|----|
|  0 |
|  1 |
|  2 |
|  3 |

(ds/select-rows new 4)
=> _unnamed [1 1]:

| :a |
|----|
|  4 |
```

**Comment by cnuernber** [comment]
Agreed, this should error out.  It does still reference the original things, however. To eliminate that you can clone the dataset.
