### ISSUE TITLE
write-csv! misses possibility to set CsvWritter settings

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#144]
I was hit again by the "maxCharsPerColumn (defaults to 4096)" issue of the univocity  parser.
This applies as well to a CsvWriter.

The current code cuts silently longer strings.

I saw you solved it partially by
defaulting to  max-chars-per-column (* 64 1024) for reading.

Thinking about it, it should be set (in my view), even higher.

This is a very dangerous "issue" of the univocity parser, as it might relate to silent data loss...
As it "cuts" my long string, the correct "quoting" failed, and so it produces even invalid csv ....

I read the comments about it, but in my view it is better to have the JVM crashed, then loosing data silently...

Maybe t.m.d could even "check" the values are not longer then the max before writing and fail accordingly...
But that would not help for reading.
(but it could warn if a value gets read and it has exactly(or more or less) the length of the configured max... this could mean it was cut off)

We should at least allow to set it for the write-csv! as well.

**Comment by behrica** [comment]
We might add it as a more clear warning into the documentation of the methods as well

**Comment by cnuernber** [comment]
IMO it should error and allow setting the value.  I agree that silently failing is a seriously bad condition.  This is pretty high priority.

The new function is named write! btw.  And it handles nippy :-).

**Comment by harold** [comment]
Not to derail this, but I've similarly wanted to pass options to do things like force quoting every field. So, if that gets in there too, that'd be great.

**Comment by cnuernber** [comment]
I mean, the other option no one is talking about is to implement the csv system and design it with performance in mind like the ability to mmap and read unescaped text more or less 'in place'.

The limits of univocity are not necessary in order to get high performance.  Their reasoning is just bad.  It is all dependent upon how much work everyone wants to do :-).

**Comment by cnuernber** [comment]
https://techascent.github.io/tech.ml.dataset/tech.v3.dataset.html#var-write.21
