### ISSUE TITLE
arrow/read-stream-dataset fails randomly arrow file

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#146]
I have one arrow file, on which repeated execution of the same code fails "sometimes", randomly.

```
(arrow/read-stream-dataset-copying
 "./allscreenings/screenings_9/BIOCONTAM_EFSA-Q-2015-00028_DIOX_NP_07/screenings.arrow"
 {:resource-type :gc}
 )
```

Hitting C-x C-e in cider on this line, gives an error on every 5th execution more or less:

```
Caused by java.lang.IllegalArgumentException
   No implementation of method: :convertible-to-reader? of protocol:
   #'tech.v3.datatype.protocols/PToReader found for class: nil

          core_deftype.clj:  583  clojure.core/-cache-protocol-fn
          core_deftype.clj:  575  clojure.core/-cache-protocol-fn
             protocols.clj:  124  tech.v3.datatype.protocols/eval14943/fn/G
                  list.clj:  196  tech.v3.datatype.list/eval18276/fn
              MultiFn.java:  244  clojure.lang.MultiFn/invoke
   copy_make_container.clj:   46  tech.v3.datatype.copy-make-container/eval18196/fn
              MultiFn.java:  244  clojure.lang.MultiFn/invoke
   copy_make_container.clj:  105  tech.v3.datatype.copy-make-container/make-container
   copy_make_container.clj:   96  tech.v3.datatype.copy-make-container/make-container
   copy_make_container.clj:  132  tech.v3.datatype.copy-make-container/->array-buffer
   copy_make_container.clj:  116  tech.v3.datatype.copy-make-container/->array-buffer
   copy_make_container.clj:  153  tech.v3.datatype.copy-make-container/->array
   copy_make_container.clj:  145  tech.v3.datatype.copy-make-container/->array
   copy_make_container.clj:  168  tech.v3.datatype.copy-make-container/->byte-array
   copy_make_container.clj:  165  tech.v3.datatype.copy-make-container/->byte-array
              datatype.clj:  117  tech.v3.libs.arrow.datatype/varchar/reify
                  copy.clj:   49  tech.v3.datatype.copy/generic-copy!/fn
                  copy.clj:   -1  tech.v3.datatype.copy/generic-copy!/fn
                   for.clj:   53  tech.v3.parallel.for/indexed-map-reduce/fn/callable
                  AFn.java:   18  clojure.lang.AFn/call
         ForkJoinTask.java: 1448  java.util.concurrent.ForkJoinTask$AdaptedCallable/exec
         ForkJoinTask.java:  290  java.util.concurrent.ForkJoinTask/doExec
         ForkJoinPool.java: 1020  java.util.concurrent.ForkJoinPool$WorkQueue/topLevelExec
         ForkJoinPool.java: 1656  java.util.concurrent.ForkJoinPool/scan
         ForkJoinPool.java: 1594  java.util.concurrent.ForkJoinPool/runWorker
 ForkJoinWorkerThread.java:  183  java.util.concurrent.ForkJoinWorkerThread/run
```

Same for "inplace".

I tried for one of your example files, "ames.pyarrow.stream" , but there it works allways.

**Comment by behrica** [comment]
I used the R package, and it reads the file without problems.

**Comment by cnuernber** [comment]
Is that file prohibitively large?  Could I get to it via some pathway?

**Comment by behrica** [comment]
Not too large: https://www.dropbox.com/s/cejbfnowg2xyerh/screenings.arrow?dl=0

Link is valid one week.

**Comment by behrica** [comment]
I observed the JVM and I am pretty sure, we have as well memory leak, each time the exception is thrown.
Each time the exception is thrown, I get a substantial increase in memory usage, which is not cleaned up by GC

**Comment by behrica** [comment]
There is timing component in it.

It happens more often, when I call read-stream-dataset-inplace quickly one after each other (same file, or different files):

If I leave 5 seconds between the invocations, is less frequent.

The best way to reproduce is probably with a directory of arrow files, and read them in as quick as possible.
(using a lazy sequence makes it worse as well....)

**Comment by cnuernber** [comment]
I found the issue.  It is way deep in tech.resource when I am trying to ensure the source native buffer cannot get cleaned up before a sub-buffer.  WeakReferences and SoftReferences are hard things to reason about as they have some counter intuitive gc behavior.

**Comment by cnuernber** [comment]
This is a great issue.  Fantastic in fact that you found this in a reproduceable way.

**Comment by cnuernber** [comment]
`5.00-alpha-9` should fix this issue.  It did in the tests on my machine.
