### ISSUE TITLE
writing gzipped nippy stores ungzipped file

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#148]
```clojure
(api/write! DS "output.nippy")
(api/write! DS "output.nippy.gz")
```

```sh
$ ls -la output.nippy* | awk '{print $9, $5}'
output.nippy 746
output.nippy.gz 746
```

**Comment by cnuernber** [comment]
Lol, that should probably be an error :-).  Gzipping a nippy file isn't going to get you much :-).

**Comment by genmeblog** [comment]
I need to check in larger datasets but it seems that nippy are compressible quite well. Just to consider.

**Comment by cnuernber** [comment]
Nippy is amazing especially when your dataset contains many duplicates as happens often in random corporate datasets.

It isn't documented via the freeze method but it also includes different compressors:
* https://github.com/ptaoussanis/nippy/blob/master/src/taoensso/nippy.clj#L1705
* argument is passed in [freeze](https://github.com/ptaoussanis/nippy/blob/master/src/taoensso/nippy.clj#L1282)

And encryption (which is documented) :-).
