### ISSUE TITLE
reading arrow files not working on JDK 14

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#150]
I tied to read the arrow files on a more recent JDK and it fails.

```
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by xerial.larray.mmap.MMapBuffer (file:/home/carsten/.m2/repository/org/xerial/larray/larray-mmap/0.4.1/larray-mmap-0.4.1.jar) to field java.io.FileDescriptor.fd
WARNING: Please consider reporting this to the maintainers of xerial.larray.mmap.MMapBuffer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Syntax error (IllegalStateException) compiling at (REPL:1:23).
Failed to find constructor f java.nio.DirectByteBuffer: $s
```

**Comment by cnuernber** [comment]
Currently my focus is jdk-8.  I will not have time to address this issue in the near future although I agree it is an issue.

**Comment by behrica** [comment]
Ok.
The xerial.larray librray is not jdk 14 compatible, I would say.

By looking at jdk14, it seems there is now a direct way to mmap larger files in Java:

https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/nio/channels/FileChannel.html#map(java.nio.channels.FileChannel.MapMode,long,long)

This could mean, that we don't need xerial.larray on new JDKs

**Comment by cnuernber** [comment]
ByteBuffers use integers for get/set/  So you can map up to 2G of a large file using the filechannel pathway and that is it.

**Comment by cnuernber** [comment]
Javacpp builds the C++ version of the arrow toolkit: https://github.com/bytedeco/javacpp-presets/tree/master/arrow

Using this pathway also gets us parquet support and parquet->arrow conversion.  Perhaps that is a way forward.

**Comment by behrica** [comment]
You think this is well maintained ?
There is an arrow 2.0 just released.

I never saw this javacpp stuff. Am I correct to say, that this is in general a way to generate working java code from a C++ library / API ?

**Comment by behrica** [comment]
Maybe this could work as an alternative to larray ?
https://arrow.apache.org/docs/java/reference/org/apache/arrow/memory/ArrowBuf.html

This seems to support "long" for addressing.

**Comment by cnuernber** [comment]
IT does but you need a function that takes a string filename and produces that long address: https://techascent.com/blog/memory-mapping-arrow.html.  I think what is missing is more fundamental than that; basically in Java 14 they removed a private constructor that allowed you to take a memory address and create a direct byte buffer from it.  Without this we cannot load arrow files using the lower level flatbuffer descriptions as they all work on nio buffers - which I think is foolish.

Javacpp is definitely well maintained.  Your analysis is correct and it is now used as the basis of tensorflow java.  We have used javacpp forever: https://github.com/techascent/tech.opencv.

**Comment by cnuernber** [comment]
I also have to say that I have tried to tell the Clojure community about javacpp for literally years.  I talked about it in the first ML talk, many posts on slack, etc etc.

Check out the entire set of libraries:

https://github.com/bytedeco/javacpp-presets

It (more or less) works :-).  And I already paid the price to figure out the 'less' portion as I used javacpp in Cortex.

**Comment by behrica** [comment]
JDK 14 contains a preview feature, 

https://openjdk.java.net/jeps/393

and I got it working on a current jdk 14.

```clojure
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.MemoryAddress;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.nio.file.Path;

public class Main {
    public static void main(String[] args) throws IOException {
        MemorySegment memorySegment = MemorySegment.mapFromPath(Path.of("/home/carsten/tmp/big_3M.arrow"),
                4396691352L, FileChannel.MapMode.PRIVATE);
        long size = memorySegment.byteSize();
        System.out.println("size = " + size);
        MemoryAddress baseAddress = memorySegment.baseAddress();
        System.out.println("baseAddress = " + baseAddress);
        MemorySegment slice = memorySegment.asSlice(0, 1000);
        System.out.println("slice = " + slice);
        byte[] bytes = slice.toByteArray();
        System.out.println("bytes = " + bytes);

// fails, as too large for ByteBuffer
//        ByteBuffer byteBuffer = memorySegment.asByteBuffer();
//        System.out.println("byteBuffer = " + byteBuffer);
    }

}
```

**Comment by cnuernber** [comment]
That is perfect.  That would definitely work.

**Comment by cnuernber** [comment]
Assuming a memory address has a transformation to long.

**Comment by behrica** [comment]
Something to think about.
At least there is an supported way comming to java.

For the records: 
On JDK 14,15, the feature needed to be enabled with specific command line settings.
It might come to JDK 16 as standard feature.
