### ISSUE TITLE
arrow file produced by R function arrow::write_dataset fails to read by t.m.d

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#153]
I am using the write_dataset function from R package arrow to write arrow files.
I cannot  get any of the files to be read in by t.d.m.

the R package has as well quite some confusion in the
[files.zip](https://github.com/techascent/tech.ml.dataset/files/5448639/files.zip)

 "naming" between

- ipc
- feather
- arrow

I asked the function arrow::write_dataset to write it in the three formats, but it produced always the same file I believe, see attached.
None of it can be opened by any t.d.m function for arrow.

On R side, I can read it back in with "read_feather" and "read_arrow", but not with "read_ipc_stream". As all three files are the same, so the same result for all files.

But I can produce "arrow" files readable from t.d.m, by arrow::write_ipc_stream(),
but not via arrow::write_dataset(format="ipc")

**Comment by behrica** [comment]
The file I send you seem to be in the "IPC file format" as depiced here:
https://github.com/apache/arrow/blob/master/docs/source/format/Columnar.rst#serialization-and-interprocess-communication-ipc

**Comment by cnuernber** [comment]
Yes, currently t.m.d is only compatible with the stream format.  The java arrow SDK crashes itself trying to read the `file` format but I am not against supporting it in in-place mode.  Thanks for the file, I will add it to the test corpus :-).

**Comment by behrica** [comment]
Maybe we want to review the "namings" of existing methods.

I got as well rather confused between the three different namings of the "type".
The R package talks about

"arrow"
"feather"
"ipc"

and then the variants of "file" and "stream".

T.d.d  adds to this "in_place" and "copying".

**Comment by cnuernber** [comment]
You can thank arrow for the first three.  Only stream is supported and the java SDK has no support for 'feather' which I gather is some compressed variant.

**Comment by cnuernber** [comment]
Not going to fix this.  One pathway from Arrow is enough to support for now much less three.
