### ISSUE TITLE
Reproducible shuffle

### ISSUE THREAD

**Issue by daslu** [techascent/tech.ml.dataset#155]
Currently, `tech.v3.dataset.modelling/k-fold-datasets` and `tech.v3.dataset.modelling/train-test-split` use `clojure.core/shuffle` for randomization.

https://github.com/techascent/tech.ml.dataset/blob/a3ba8749cb54fa14a061c3a02f34893a63d8e690/src/tech/v3/dataset/modelling.clj#L138

https://github.com/techascent/tech.ml.dataset/blob/a3ba8749cb54fa14a061c3a02f34893a63d8e690/src/tech/v3/dataset/modelling.clj#L158

To allow for reproducible experiments, it may be useful to use an explicit seed for the shuffle. Here is one way to do it, using [data.generators](https://github.com/clojure/data.generators):
```
(require '[clojure.data.generators :as gen])

(defn shuffle-with-seed
  "Apply a deterministic pseudorandom permutation to sequential data."
  [seed data]
  (binding [gen/*rnd* (rng seed)]
    (gen/shuffle data)))
```

**Comment by cnuernber** [comment]
brilliant, yes the seed should be argument and if provided shuffle should be reproducible.  Very nice, thanks!
