### ISSUE TITLE
which date/time formats should work with read-stream-dataset-inplace ?

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#158]
I created some arrow files containing date types and could not really figure out, which date types are supported by TDM read-arrow-dataset-inplace function.
Some failed, that I saw.

I saw the code, but couldn't really sea, which ones are currently support for the "in-place" case.

**Comment by cnuernber** [comment]
They should all work with the caveat that they will be converter to X-since-epoch form, usually millisecond since epoch.
