### ISSUE TITLE
specific parquet file fails to be written as arrow

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#159]
Reading the attached parquet file with `parquet->ds-seq` and writing it with `arrow/write-dataset-to-stream` fails.

It has a single row, and one column is nil, that's maybe why.
```
Execution error at tech.v3.datatype.native-buffer/wrap-address (native_buffer.clj:644).
Attempt to wrap 0 as an address for a native buffer
```

[part-00000-74d3eb51-bc9c-4ba5-9d13-9e0d71eea31f.c000.snappy.parquet.gz](https://github.com/techascent/tech.ml.dataset/files/5481329/part-00000-74d3eb51-bc9c-4ba5-9d13-9e0d71eea31f.c000.snappy.parquet.gz)

**Comment by cnuernber** [comment]
Great testcase, this is really helpful, thanks!
