### ISSUE TITLE
consider to parse date/time formats from arrow as local-date

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#161]
Similar to parsing CSV files.
Arrow has precise types, it would be a 
[with_date.arrow.gz](https://github.com/techascent/tech.ml.dataset/files/5483845/with_date.arrow.gz)
pitty not to use them.

**Comment by cnuernber** [comment]
Agreed but I did not think it had precise types specifically for local date.  It would be very awesome if I am mistaken :-).
