### ISSUE TITLE
Syntax error (ClassNotFoundException) when requiring tech.v3.dataset

### ISSUE THREAD

**Issue by kommen** [techascent/tech.ml.dataset#162]
To reproduce:

```bash
clj -Sdeps '{:deps {techascent/tech.ml.dataset {:mvn/version "5.00-alpha-21"}}}' -e "(require '[tech.v3.dataset :as ds])"  
```

=> `Syntax error (ClassNotFoundException) compiling at (tech/v3/libs/smile/data.clj:226:1).`

The issue didn't exist with version `5.00-alpha-20`

**Comment by cnuernber** [comment]
Hmm, thanks for the quick bug report and clean repro.  Looking at this now.

**Comment by cnuernber** [comment]
Lol, trying to support Spark, arrow, and smile and not have dep nightmares is a stretch :-).
