### ISSUE TITLE
large arrow file fails on read-stream-dataset-copying

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#163]
```clojure
1. Caused by java.lang.UnsupportedOperationException
   count not supported on this type: LargeVarCharVector

                   RT.java:  671  clojure.lang.RT/countFrom
                   RT.java:  643  clojure.lang.RT/count
                  base.clj:  425  tech.v3.datatype.base/eval16804/fn
             protocols.clj:   50  tech.v3.datatype.protocols/eval13434/fn/G
                  base.clj:   67  tech.v3.datatype.base/ecount
```

Looking at the code it seems that TMD misses currently support for LargeVarBinaryVector and LargeVarCharVector.

The arrow file to reproduce it should be the same as #147

**Comment by cnuernber** [comment]
OK, will check it out, thanks :-).  These types of issues have been really helpful, I am really glad you have the patience to find and file them.

**Comment by cnuernber** [comment]
Not sure I want to fix this.  Copying copies the entire file into process memory and on my laptop that guarantees a C OOM situation for the big test file.

**Comment by cnuernber** [comment]
C OOM situations are considerably more unpredictable than Java OOM situations.  Once the C subsystem runs out of memory sometimes you can't throw exceptions or safely unwind the stack.

**Comment by behrica** [comment]
I think there can be "small files", having a LargeVarCharVector.
I believe, I can create a very small file with  a LargeVarCharVector.

It is a decision of the tool which generates the arrow file, under which circumstances it chooses the VarCharVector vs. te LargeVarCharVecor.

So not supporting "at all" the LargeVarCharVector is quite a limitation of the "arrow" support, I would say.

**Comment by cnuernber** [comment]
It is supported for in-place.  Do you know the difference between the two, specifically, in the data?   Maybe it would behoove you to do some research and figure out the actual binary difference.  Once there I think you would find this issue just isn't that big of a deal.  It is also straightforward to support when the time comes.

Closing unless you can produce a file less than 4GB in size with that column format :-).

**Comment by behrica** [comment]
I have a small file which reproduces the error, 352 bytes.
I commited it here and added a test:
https://github.com/behrica/tech.ml.dataset/tree/LargeVarCharTest

If you want, I make a PR, so you have test and file.
