### ISSUE TITLE
specified parquet depdency fail for me

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#168]
```clojure
org.apache.parquet/parquet-hadoop {:mvn/version "1.11.0"}
org.apache.hadoop/hadoop-common {:mvn/version "3.1.1"}
```
fails with NoClassDefFound ParquetFielWriter  when writing parquet file

(I added only parquet deps, not parquet + arrow)

working:

```
org.apache.parquet/parquet-hadoop {:mvn/version "1.10.1"
 org.apache.hadoop/hadoop-common {:mvn/version  "3.2.0"}
```

**Comment by cnuernber** [comment]
OK, that is a bug.  That should work.

**Comment by cnuernber** [comment]
It does work: https://github.com/cnuernber/simpledata/tree/simple-parquet

I can require tech.v3.libs.parquet and tech.v3.dataset and load parquet files.

**Comment by behrica** [comment]
The issue went away for my project as well.
We can close it.
