### ISSUE TITLE
column-map doesn't infer returning type

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#169]
When I want to convert a column without providing target datatype, original one is reused. IMHO it should be infered from the returning values. I can't not always provide target datatype.

```clojure
(def ds (tech.v3.dataset/->dataset {:a ["1;2;3;4;5"]}))

(tech.v3.dataset.column/column-map #(mapv read-string (clojure.string/split % #";")) nil (ds :a))
;; => #tech.v3.dataset.column<string>[1]
;;    :_unnamed
;;    [[1 2 3 4 5], ]

;; string indeed, should be vector of strings
(clojure.core/first (tech.v3.dataset.column/column-map #(mapv read-string (clojure.string/split % #";")) nil (ds :a)))
;; => "[1 2 3 4 5]"

(def ds2 (tech.v3.dataset/->dataset {:a ["1" "2" "3" "4"]}))

(tech.v3.dataset.column/column-map read-string nil (ds2 :a))
;; => #tech.v3.dataset.column<string>[4]
;;    :_unnamed
;;    [1, 2, 3, 4, ]

(tech.v3.dataset.column/column-map read-string :int64 (ds2 :a))
;; => #tech.v3.dataset.column<int64>[4]
;;    :_unnamed
;;    [1, 2, 3, 4, ]
```

**Comment by cnuernber** [comment]
Clojure fns do not have their return type associated into their metadata.  I believe this is literally impossible.

**Comment by genmeblog** [comment]
Maybe I'm wrong (it happens lately :) ) but I think it worked this way in 4.x versions.

**Comment by cnuernber** [comment]
With no datatype passed it unifies the datatypes of the incoming *columns* but not the input *function*.

I have other tools where I would also like the inference based on the function.  This is a totally valid issue in that sense but I do not thing it is solveable unless you define an alternate 'fn' operator that adds metadata about the return type.

I do this for TVM but I still cannot infer return value type.  Luckily their AST nodes know their type so I can ask the returned ast node what datatype it is if I want to know this.

**Comment by genmeblog** [comment]
Ok, need to rethink arguments to my wrapper then. Thanks.
