### ISSUE TITLE
iterator-seq memory leak (with surprising results)

### ISSUE THREAD

**Issue by joinr** [techascent/tech.ml.dataset#17]
Just documenting here what I found regarding the possible memory leak due to cached sequences in [tech.ml.dataset.parse/csv->columns](https://github.com/techascent/tech.ml.dataset/blob/v2/src/tech/ml/dataset/parse.clj#L280).

Retaining the head of the invoked `iterator-seq` on the iterable produced by the univocity CSV parser should result in e.g. large text files being fully realized and cached until after the dataset is constructed and the function returns.  In theory, this would trivially blow the heap (e.g. 1GB of string references could expand to significantly more in memory, etc.).

I tested with the corrected test data, using a filesize of 1GB with the legacy (leaky) implementation.  I then tested with the proposed fix that uses an atom to clear the reference later, [here](https://gist.github.com/joinr/62591119cc1fb7d5bef988617a8f2cd7).  

For a baseline file of ~1.3GB, the dataset is able to load in both cases in about the same time.  More importantly, the memory footprint and GC pressure is fairly consistent, with the freed implementation having a bit less (around 1.5gb max used).  It looks like univocity's CSV parser is returning many flyweight objects for the rows in its iterable, rather than actual arrays of strings, since the memory footprint is surprisingly low.  So, the typically destructive caching behavior doesn't impact us at this scale.

To test this further, I pumped the row count for the synthetic data, and generated a 13.4 GB dataset to load.  On a 4GB heap, we do see a difference in the memory profile, but again not drastic.  Both implementations peak out around 3GB eventually, with the leaking version running into GC issues earlier.  Consequently, the non-leaking version is around 5% faster to load the dataset.  Both datasets load on a 4GB heap though, which is actually fairly impressive.

In all, I think this is a minor issue since univocity's parsing implementation appears to be efficient, thus mitigating the effects of the leak.  For implementation sake, it's probably fine to leave it as is, unless people run into problems in the far future.  In the extreme, say someone is trying to load a file that vastly outstrips available memory (say 100GB),  it may be a problem, but at that point there are likely smarter options for processing.  For laptop use cases, the existing solution appears to scale fine.

**Comment by cnuernber** [comment]
I think that iterator-seq in this case works.  The iterator isn't sitting on a collection but on a function that mutable returns string[] objects until finished.  So if iterator-seq doesn't hold onto head a sequence based on this iterator doesn't automatically reference the entire set of returned values.

iterator-seq calls chunkIteratorSeq:
https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/RT.java#L516

This I think is fine.  

Then we have the code in the actual csv->columns function.  The question is if the doseq holds onto head and I am certain that it does not.  Now, the question becomes can the garbage collector get rid of data during the doseq process.  

Because nothing in the doseq references data (nor anything else after the doseq) I think data is getting GC'd during parsing.

**Comment by joinr** [comment]
Yeah, I was going off the original docs and general seq behavior [defined here](Seqs cache values, thus iterator-seq should not be used on any
iterator that repeatedly returns the same mutable object.).  Specifically, "Seqs cache values, thus iterator-seq should not be used on any iterator that repeatedly returns the same mutable object."  This caching behavior is my expectation; even the chunkseq will just dump the chunks into an array or vector I think.  If they were caching string[] array objects for each line, I'd figure we would see a cached seq of string[] of the full file length, which would likely wreck the heap under the tests I performed (given all the novel string objects).

The calls to [ChunkedCons](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/RT.java#L524) inside of the chunkIteratorSeq indicate that there's caching.  I'm just really surprised I wasn't able to blow the heap given that there "should" be like millions of strings retained across all those string arrays being cached.  Otherwise it's not a persistent, immutable sequence of values.

That this didn't happen is a happy coincidence (or maybe there's a bug in `iterator-seq` that's causing it no to cache, I haven't looked to hard).  It looks like the univocity implementation does indeed just return a string[] (unless there's internal caching or pooling going on there too, doesn't seem to be).

`doseq` should not hold a reference since it expands into a `loop` form that processes the sequence in chunks as well.  So, the the local loop bindings are being directed toward  `rest or `chunk-rest` as the iteration progresses, which frees up references to predecessors.  Willing to bet my paycheck `doseq` will not cause a leak.  `iterator-seq` on the other hand has my somewhat mystified based on the source and working knowledge.

**Comment by joinr** [comment]
May be some unexpected behavior around chunkIteratorSeq akin to the stuff Peter Nagy brought up in this [zulip thread](https://clojurians.zulipchat.com/#narrow/stream/151168-clojure/topic/laziness).

**Comment by cnuernber** [comment]
Closing this because we couldn't find a leak :-).
