### ISSUE TITLE
dfn/fixed-rolling-window: set to the right edge of the window instead of the center

### ISSUE THREAD

**Issue by alex314159** [techascent/tech.ml.dataset#173]
Hi Chris,

Using `[tech.v2.datatype.functional :as dfn]`, fixed-rolling-window centers the window in the middle. This is confusing especially if you're used to time series analysis where for instance you want to calculate a moving average. Could you add an option to center on the right? (pandas provides both options but defaults to the right https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rolling.html)

```
(dfn/fixed-rolling-window 5 (fn [w] (last w)) (range 20))
=> [2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 19 19]

(dfn/fixed-rolling-window 5 (fn [w] (dfn/mean w)) (range 20))
=> [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 17 18]

```

Separately (and this might be fixed in v3, still using v2), min and max don't work for me:

```
(dfn/min (range 20))
Execution error at tech.v2.datatype.builtin-op-providers/get-op (builtin_op_providers.clj:42).
Failed to find op: :min
```

Looking at the code sounds like a change in the pad-sequence
```
(->> (pad-sequence n-pad item)
                     (fixed-window-sequence window-size 1)
                     (pmap window-fn))
```
might be enough?

Thank you!

**Comment by cnuernber** [comment]
Answering in reverse order:

I think what you want is `reduce-min` as opposed to `min`.  `min` would work if you had two vectors and wanted to produce a new vector with the minimum values while the `reduce` versions were there so you could take a vector and produce a scalar.

Adding an option to center on the right sounds completely reasonable to me.   The underlying reader code repeats the end value so you can safely run off the end at either direction so we can safely adjust which way the window expands from the index.

**Comment by alex314159** [comment]
Thank you Chris. Would something like this work, using `indexed-reader`? Gets the desired result but seems to break laziness by counting the item size

```
(defn fixed-rolling-window
  "Return a lazily evaluated rolling window of window-fn applied to each window.  The
  iterable or sequence is padded such that there are the same number of values in the
  result as in the input.
  If input is an iterator, output is an lazy sequence.  If input is a reader,
  output is a reader.
  options: :center false will center on the right
  "
  ([window-size window-fn item options]
   (fixed-rolling-window window-size window-fn item {:center true}))
  ([window-size window-fn item options]
   (let [n-pad (quot (long window-size) 2)
         shift (if (:center options) 0 (if (even? window-size) (dec n-pad) n-pad))
         c (count item)]
     (case (argtypes/arg->arg-type item)
       :scalar (throw (ex-info "Rolling windows aren't defined on scalars" {}))
       :iterable (->> (pad-sequence n-pad item)
                      (fixed-window-sequence window-size 1)
                      (pmap window-fn))                     ;TODO right center
       :reader
       (dfn/indexed-reader (range (- shift) (- c shift)) ;TODO import indexed-reader
         ((get window-reader-table (casting/safe-flatten
                                             (dtype-base/get-datatype item)))
                  window-size (dtype-base/get-datatype item) item window-fn n-pad))

       ))))
```

**Comment by cnuernber** [comment]
Indexing will always work but I would first recommend you move to v3 and then we can just change the v3 windowed-reader.  There is only one of them and it isn't a macro'd object:

https://github.com/cnuernber/dtype-next/blob/master/src/tech/v3/datatype/rolling.clj#L79

In that case we can just change the value of n-pad.  If it is zero, then your results should be right-centered and if it is window-size then your result would be left-centered.

Using an indexed reader will definitely work.

**Comment by cnuernber** [comment]
https://cnuernber.github.io/dtype-next/tech.v3.datatype.rolling.html - docs should be up soon if not already.

**Comment by alex314159** [comment]
Thank you so much Chris - this is great!!!

**Comment by alex314159** [comment]
Actually sorry to bug you again with this but I don't think this isn't exactly working as intended:

The `{:relative-window-position :right}` is fine but the `{:relative-window-position :left}` which is akin to the pandas right option and the "logical" thing for time series seems to be one index too much to the left

```
(rolling/fixed-rolling-window (range 20) 5 (fn [w] (first w)) {:relative-window-position :right} )
=> [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19]
(rolling/fixed-rolling-window (range 20) 5 (fn [w] (last w)) {:relative-window-position :right} )
=> [4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 19 19 19 19]

(rolling/fixed-rolling-window (range 20) 5 (fn [w] (first w)) {:relative-window-position :left} )
=> [0 0 0 0 0 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14]
(rolling/fixed-rolling-window (range 20) 5 (fn [w] (last w)) {:relative-window-position :left} )
=> [0 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18]
```
The last window should be [15 16 17 18 19] so you can easily calculate, for a stock price, "lowest price over 5 sessions" or "average price over 5 sessions".

**Comment by cnuernber** [comment]
You are exactly right.  I have a [fencepost error](https://xkcd.com/1171/)!.
