### ISSUE TITLE
recommend result of join-by-column be something that implements PColumnarDataset; Indexing error in :join-table result

### ISSUE THREAD

**Issue by joinr** [techascent/tech.ml.dataset#18]
Went to implement a naive left-join and corresponding test, working off the [ww3 sample](https://www.w3schools.com/sql/sql_join_left.asp)

Using the following data:
lhs 

[{"CustomerID" 1,
  "CustomerName" "Alfreds Futterkiste",
  "ContactName" "Maria Anders",
  "Address" "Obere Str. 57",
  "City" "Berlin",
  "PostalCode" 12209,
  "Country" "Germany"}
 {"CustomerID" 2,
  "CustomerName" "Ana Trujillo Emparedados y helados",
  "ContactName" "Ana Trujillo",
  "Address" "Avda. de la Constitución 2222",
  "City" "México D.F.",
  "PostalCode" 5021,
  "Country" "Mexico"}
 {"CustomerID" 3,
  "CustomerName" "Antonio Moreno Taquería",
  "ContactName" "Antonio Moreno",
  "Address" "Mataderos 2312",
  "City" "México D.F.",
  "PostalCode" 5023,
  "Country" "Mexico"}]

rhs

[{"OrderID" 10308,
  "CustomerID" 2,
  "EmployeeID" 7,
  "OrderDate" "1996-09-18",
  "ShipperID" 3}
 {"OrderID" 10309,
  "CustomerID" 37,
  "EmployeeID" 3,
  "OrderDate" "1996-09-19",
  "ShipperID" 1}
 {"OrderID" 10310,
  "CustomerID" 77,
  "EmployeeID" 8,
  "OrderDate" "1996-09-20",
  "ShipperID" 2}]

The result of `join-by-column` is a map of :join-table and :rhs-missing, not something that can immediately be used by the ds protocols and API.  The stock `join-by-column` completes and results print apparently successfully. 

```clojure
{:join-table join-table [1 11]:

| CustomerID |                       CustomerName |  ContactName |                       Address |        City | PostalCode | Country | OrderID | EmployeeID |  OrderDate | ShipperID |
|------------+------------------------------------+--------------+-------------------------------+-------------+------------+---------+---------+------------+------------+-----------|
|          2 | Ana Trujillo Emparedados y helados | Ana Trujillo | Avda. de la Constitución 2222 | México D.F. |       5021 |  Mexico |   10308 |          7 | 1996-09-18 |         3 |
, :rhs-missing-indexes [1 2]}
```

If I try to apply the ds functions to the :join-table result, e.g. `columns`, I get an error:

```clojure
[Error printing return value (IndexOutOfBoundsException) at it.unimi.dsi.fastutil.longs.LongArrayList/getLong (LongArrayList.java:267).
Index (1) is greater than or equal to list size (1)
user> 
```
Seems like maybe this is an off-by-one error somewhere (looks like we should be getting 0 instead of 1 as an index).

Maybe the :rhs-missing information could be elevated to metadata on the join-table, so that the type of `join-by-column` is String|Keyword|Number -> PColumnarDataset -> PColumnarDataset -> PColumnarDataset ?

**Comment by joinr** [comment]
so the toString implementation of dataset works fine here, but the columns implementation is returning the off-by-one error

**Comment by joinr** [comment]
coercion to seq on individual columns from the colmap works...

**Comment by joinr** [comment]
column's .n-elems value is 3, which is tripping up the call
```clojure
 (toString [item]
    (let [format-str (if (> n-elems 20)
                       "#tech.ml.dataset.column<%s>%s\n%s\n[%s...]"
                       "#tech.ml.dataset.column<%s>%s\n%s\n[%s]")]
      (format format-str
              (name (dtype/get-datatype item))
              [n-elems]
              (ds-col-proto/column-name item)
              (-> (dtype/->reader item)
                  (dtype-proto/sub-buffer 0 (min 20 n-elems))  ;;<---here
                  (dtype-pp/print-reader-data)))))
```

Looks like the sub-buffer implementation is creating an indexed reader reading out of bounds.  n-elems should be 1...

**Comment by joinr** [comment]
I think the problem is the implementation of `select` in tech.ml.dataset.impl.column....

You assume on the fast-path that 

```clojure
(select [col idx-rdr]
    (if (== 0 (.size missing))
      ;;common case
      (Column. missing (dtype/indexed-reader idx-rdr data) n-elems metadata)  ;;<---- this is maybe wrong, n-elems may have changed in the select to be < the original dataset, or at least its usage is such...
      ;;Uggh.  Construct a new missing set
      (let [idx-rdr (typecast/datatype->reader :int64 idx-rdr)
            n-idx-elems (.lsize idx-rdr)
            result-set (HashSet.)]
        (parallel-for/serial-for
         idx
         n-idx-elems
         (when (.contains missing (.read idx-rdr idx))
           (.add result-set idx)))
        (Column. result-set (dtype/indexed-reader idx-rdr data)
                 n-idx-elems metadata))))
```

**Comment by joinr** [comment]
Looking at changing to leverage the idx-reader's count, 

```clojure
(Column. missing (dtype/indexed-reader idx-rdr data) (dtype/ecount idx-rdr) metadata)
```

**Comment by cnuernber** [comment]
Fixed by: https://github.com/techascent/tech.ml.dataset/commit/3b69792349d913d6e334c13ae382da3c894d7079
