### ISSUE TITLE
v5 ds/->dataset fails on reading csv input stream

### ISSUE THREAD

**Issue by alex314159** [techascent/tech.ml.dataset#180]
Hello,

not sure if real issue or me doing something wrong, but I have quite a few bz2 files (from Python) which I used to read like that in v4:

```
(defn bz2->dataset
  ([file max-cols]
   (let [input-stream (-> file
                          (client/get {:as :stream})
                          (deref)
                          (:body)
                          (BZip2CompressorInputStream.)
                          (io/input-stream))]
     (ds/->dataset input-stream {:max-num-columns max-cols}))) ;; fails here
  ([file] (bz2->dataset file 8192)))
```

This fails in v5 with the following:
```
Execution error at tech.v3.dataset.io/eval23570$fn (io.clj:43).
Unrecognized read file type: null
```

However it works if I replace the `ds/->dataset` call with:
`(tech.v3.dataset.io/data->dataset input-stream {:file-type :csv :max-num-columns 8192})`

**Comment by cnuernber** [comment]
Those are big.

->dataset used to default to csv file type if no file type was provided.  You can pass in a file-type to ->dataset in the options and should under-the-hood take the pathway that you show in the last example.

Perhaps ->dataset should default to :csv again no file type is provided or discoverable.  

Certainly nothing you are doing, just removed a default that perhaps I should have been more careful about.

`(ds/->dataset input-stream {:file-type :csv :max-num-columns 8192}) should do the same thing as your above example.

**Comment by alex314159** [comment]
I see! Thanks a lot! Maybe defaulting to csv would be good yes, or updating the doc to specify that file-type is necessary for input-streams - this is confusing to me (but maybe because I'm not used to streams!):
```* A `String` or `InputStream` will be interpreted as a file (or gzipped file if it
     ends with .gz) of tsv or csv data.  ```

**Comment by cnuernber** [comment]
Ah, I think I will just replace the default :-).  At least a csv default will work for *some* people.  The current setting won't work for anyone :-).

**Comment by cnuernber** [comment]
Fixed with a [documentation fix](https://techascent.github.io/tech.ml.dataset/tech.v3.dataset.html#var--.3Edataset).
