### ISSUE TITLE
replace missing filled large negative values

### ISSUE THREAD

**Issue by kimim** [techascent/tech.ml.dataset#181]
In this code, I expected to get

{:a [**1 1** 2 2]}

But it is `-4.612E+18`

```
(let [ds (ds/->dataset {:a [nil nil 2 2]})]
  (ds/replace-missing ds :all :value dfn/mean))
;; => _unnamed [4 1]:

|         :a |
|------------|
| -4.612E+18 |
| -4.612E+18 |
|          2 |
|          2 |
```

**Comment by kimim** [comment]
And lower level errors:
```

(dfn/mean (dtype/->reader (:a (ds/->dataset {:a [0 0 2 2]}))))
;; => 1.0
(dfn/mean (dtype/->reader (:a (ds/->dataset {:a [nil nil 2 2]}))))
;; => -4.6116860184273879E18

```

**Comment by cnuernber** [comment]
Definitely this is an issue, thanks for filing it with such a clear reproducible pathway.

**Comment by cnuernber** [comment]
What you would get would be 2 as it is currently designed.

Replace missing, when calculating the mean does not use the missing values at all.  They are dropped including in the count of elements.  So your mean calculation will be 4/2 as  2 values should be dropped -- not 4/4 filling in zeros for missing values.

**Comment by cnuernber** [comment]
This behavior I think is debatable for sure but it is sort of a standard to drop the missing values in statistics packages.

For instance, the apache commons math library has these settings for [missing values[(https://github.com/apache/commons-math/blob/16abfe5de688cc52fb0396e0609cb33044b15653/src/main/java/org/apache/commons/math3/stat/ranking/NaNStrategy.java).

What you are seeing is the long missing value, Long/MIN_VALUE, being added into means which is incorrect for sure IMO but it does correspond in some sense to the MINIMUM nan strategy above.

**Comment by cnuernber** [comment]
The new version with the fix is up.  Try it out and let's keep discussing things here if it doesn't work for you :-).

**Comment by kimim** [comment]
Thank you for fast response. Missing value and count are dropped together is reasonable. Is it possible to add a parameter to let user choose that missing slots in numeric column are counted. But this will introduce additional complexity. That's difficult to design.
