### ISSUE TITLE
Data type for column

### ISSUE THREAD

**Issue by kimim** [techascent/tech.ml.dataset#187]
Firstly, create column with vec and int array, then convert to double array:
```clojure
  (let [col1 (col/new-column :col1 [1 2 3])]
    (col/to-double-array col1))
  (let [col1 (col/new-column :col1 (int-array [1 2 3]))]
    (col/to-double-array col1)))
```
the former one will throw an exception:

```
1. Unhandled java.lang.Exception
   Non-numeric columns do not convert to doubles.
```

**Comment by cnuernber** [comment]
Definitely an issue; that detection should only error if the column is definitely not numeric (string, keyword).

**Comment by kimim** [comment]
It seems some update needed in dtype-next:

```clojure
(extend-protocol PElemwiseDatatype
  Object
  (elemwise-datatype [item] :object)
  ElemwiseDatatype
  (elemwise-datatype [item] (.elemwiseDatatype item)))
```

**Comment by cnuernber** [comment]
if you (map meta (vals ds)) the :datatype entry is the return value of `tech.v3.datatype/elemwise-datatype`.  This is the datatype.

The Object overload only gets called if no derived classes themselves implement PElemwiseDatatype.  This is the base implementation but tech.v3.datatype.Buffer classes all implement the java interface ElemwiseDatatype with a default implementation.
