### ISSUE TITLE
allow selector-fn for remove, drop and select columns

### ISSUE THREAD

**Issue by kimim** [techascent/tech.ml.dataset#188]
In PR #186, `update-columns` now accepts column name seq and a column filter fn to select the columns.
There are still three similar functions:
- `remove-columns`
- `drop-columns`
- `select-columns`

Shall we also make them accept column filter fn as second parameter? If you decide to add this feature, I'm glad to create a PR with unit tests.

**Comment by cnuernber** [comment]
Yes lets do it

**Comment by kimim** [comment]
Updated in PR #189
