### ISSUE TITLE
add support for big text storage via mmaped file ?

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#190]
As a followup of our conversation here:
https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/store.20text.20columns.20in.20mmaped.20file

I made some "helper methods", which allow to have a text column in a tech.ml.dataset,
which is "backed" by a mmaped file.
The user level code would look like this:

```clojure
(def mmap-file-name "/tmp/abstract-column.bin")

  (def ds
    (-> "./test/data/medical-text.csv"
        (ds/->dataset {:key-fn keyword
                       :column-whitelist ["cord_uid" "abstract"]
                       :max-chars-per-column 10000000
                       :parser-fn {:abstract [:object #(str->mmap % mmap-file-name )]} })
        (ds/rename-columns {:abstract :abstract-pointer})
        (add-mmap-text-column  :abstract-pointer :abstract mmap-file-name)))
```

This result in having  new 2 columns in the dataset:
 * :abstract-pointer    This contains `offset` and `length` of the string inside a mmaped file.  (maybe the filename  (or the mmap address  even) of the mmaped file could be added here as well, for clarity)
 * :abstract This is a view over the abstract-pointer column, which on-access resolves the String from the pointers + the mmap file
 
 It is a third alternative of storing Strings in a dataset, where we have :string and :text already.
 
 I tried it out with larger the RAM texts, and it behaves very well and fast in my view.
 Specially by simply "not-selecting" the 'abstract' column, we can do all operations on the dataset, without taking any performance penalty.

**Comment by behrica** [comment]
I just saw that a column can have metadata, so this might be a better place to keep the mmaped filename.
I will explore this.

**Comment by behrica** [comment]
Could I implement a   dtype/ObjectWriter  which writes bytes/Strings to a java.io.File ?

The the code could become  independent from "File" and operate on the dtype interfaces.

**Comment by behrica** [comment]
I was looking into dtype-next, so see if I could use teh concepts of ObejctWriter.
But it is not appendable, which is an issue for mu use case.

So I think it can only work with real files, as they have these are appendable.

**Comment by behrica** [comment]
Should I just summit a PR at this stage, so you can have a loot at the code ?

**Comment by cnuernber** [comment]
What I would like is an implementation of the [PrimitiveList](https://github.com/cnuernber/dtype-next/blob/master/src/tech/v3/datatype/list.clj#L100) that is backed by a file and that does an mmap call upon first read access.  This is a general datastructure that can be used outside the context of encoded text.  Once that is in place then I think pulling the encoded text class across, changing it's interface as necessary and allowing users to create columns of this type.  You would also need to be able to set the temp directory I think as options upon dataset creation.

That is just the way I think, however.  I would first want to get some simple reusable thing that solved that issue.  

I would like to see a PR as I know there are several ways to solve this issue.  I find it super encouraging that you were able to achieve this through dataset engineering in more or less very simple way already; to me it means the architecture is very malleable which I think is very important for the long run.  So it is up to you, really.

**Comment by behrica** [comment]
> What I would like is an implementation of the [PrimitiveList](https://github.com/cnuernber/dtype-next/blob/master/src/tech/v3/datatype/list.clj#L100) that is backed by a file and that does an mmap call upon first read access. This is a general datastructure that can be used outside the context of encoded text. Once that is in place then I think pulling the encoded text class across, changing it's interface as necessary and allowing users to create columns of this type. You would also need to be able to set the temp directory I think as options upon dataset creation.
Yes, this seams the right think to do.

As I was looking in dtype-next, I did not find an appendable data structure, I saw only buffer and reader
I will have a look at this.

**Comment by behrica** [comment]
I have a first working version of this.
So I do a draft PR so we can discuss on the level of the code.
