### ISSUE TITLE
Feature request: Printing all the rows of a dataset using :all option

### ISSUE THREAD

**Issue by ashimapanjwani** [techascent/tech.ml.dataset#195]
Maybe we can have :print-index-range accept an :all option which will print all the rows of the dataset.

**Comment by ashimapanjwani** [comment]
@cnuernber If you think adding this option is a good idea, I would be happy to raise a PR for this.

**Comment by cnuernber** [comment]
Very good idea.  A PR here is welcome.

**Comment by cnuernber** [comment]
This works now :-).
