### ISSUE TITLE
Feature request: view each column's datatype below the column name

### ISSUE THREAD

**Issue by ashimapanjwani** [techascent/tech.ml.dataset#196]
It can be something similar to tibbles in R

![image](https://user-images.githubusercontent.com/33724707/105722825-12a6b300-5f4c-11eb-8f7c-aebdbafd1471.png)

**Comment by ashimapanjwani** [comment]
@cnuernber If you think this is a good idea, I would be happy to raise a PR for this.

**Comment by cnuernber** [comment]
I like that a lot.  I would love a PR for this.

**Comment by cnuernber** [comment]
Fixed in #197
