### ISSUE TITLE
column-map and nil values

### ISSUE THREAD

**Issue by alex314159** [techascent/tech.ml.dataset#200]
Hello,

it looks like `ds/column-map` is filtering for rows with nil values. Is that desired behaviour? Thanks,

```
def t (ds/->dataset [{:a 1 :b 2} {:a nil :b 4}]))
=> #'jasmine.quantscreen.blpload/t
t
=> _unnamed [2 2]:

| :a | :b |
|----|----|
|  1 |  2 |
|    |  4 |

(ds/column-map t :c #(if (some? %1) %1 %2) [:a :b])
=> _unnamed [2 3]:

| :a | :b | :c |
|----|----|----|
|  1 |  2 |  1 |
|    |  4 |    |

(assoc t :c (map #(if (some? %1) %1 %2) (t :a) (t :b)))  ; what I expected to happen
=> _unnamed [2 3]:

| :a | :b | :c |
|----|----|----|
|  1 |  2 |  1 |
|    |  4 |  4 |


```

Related: the use case is exactly as above, replace missing values in a column with values from another column (I looked at `ds/replace-missing` but it seems to be doing something different).

**Comment by cnuernber** [comment]
Hmm, good idea.  The original design of column map was to produce a union of missing values of the two columns.  dtype/emap will work the way you want in terms of create a new column like that as the dtype level things do not deal at all with missing values.

**Comment by cnuernber** [comment]
Perhaps the strategy to use with missing values should be something you can specify when you perform a column-map.

**Comment by alex314159** [comment]
Ahh - I see. I think both approaches are logical. In my mind the function was just an efficient way to do `assoc ... map`, but it could be my bias from thinking the pandas `df.apply()` way. I think being able to specify the strategy would be great, or maybe just document the current missing set strategy in the docstring. `dtype/emap` works of course, thanks for pointing out!

**Comment by cnuernber** [comment]
Closing this for now - there is a sentence about the missing set in the [current documentation](https://techascent.github.io/tech.ml.dataset/tech.v3.dataset.html#var-column-map).  I think there are many possibilities here how to handle missing values is an open question.  Maybe someone will come along later with a good idea of how to address that :-).
