### ISSUE TITLE
Feature request and example code - from/to clipboard

### ISSUE THREAD

**Issue by alex314159** [techascent/tech.ml.dataset#205]
Hi,

I find myself using the following a lot - would it be worth integrating into the codebase? Thanks,

(tested on Linux / LibreOffice)
```
;in the ns part
(:import (java.io ByteArrayInputStream ByteArrayOutputStream)
           (java.awt.datatransfer DataFlavor StringSelection Transferable)
           (java.nio.charset StandardCharsets)
           (java.awt Toolkit))


;;the code
(defn clipboard []
  (.getSystemClipboard (Toolkit/getDefaultToolkit)))

(defn clipboard->dataset []
  (try
    (ds/->dataset
      (ByteArrayInputStream.
        (.getBytes (.getTransferData (.getContents (clipboard) nil) (DataFlavor/stringFlavor)) StandardCharsets/UTF_8))
      {:file-type :csv})
    (catch NullPointerException e nil)))

(defn dataset->clipboard [x]
  (let [os (ByteArrayOutputStream.)]
    (ds/write! x os {:file-type :csv})
    (let [selection (StringSelection. (String. (.toByteArray os) StandardCharsets/UTF_8))]
      (.setContents (clipboard) selection selection))))

```

**Comment by cnuernber** [comment]
Wow, very interesting.  Yes, I think it would make sense, thanks a ton for this.

**Comment by alex314159** [comment]
Thanks for the feedback! Tested with Windows and Excel today. Works but paste from clipboard into Excel makes several lines but only one column (so you need to launch the Convert Text to Columns Wizard and specify "," as separator). If you do `(ds/write! x os {:file-type :csv :separator \tab})` then it works straight away, so I guess you'd want to have the separator as an optional parameter in `dataset->clipboard`. Unfortunately I have no access to a Mac to try the same.

**Comment by harold** [comment]
I paste into google sheets frequently and it does better with `\tab`s as well. Maybe a reasonable default (.tsv)

**Comment by joinr** [comment]
Fyi, if you use this it'll crap out on systems without a clipboard implementation if you require the ns (e.g. headless systems running just the jvm with no GUI, getSystemClipboard will toss an exception).  I ran into this before and found it an unpleasant surprise.  The fix is to wrap in a try/catch, at which point the clipboard is a placeholder (trying to use it is undefined).

```clojure
(def ^Clipboard clipboard
  (try (.getSystemClipboard toolkit)
       ;;we are in a headless system..create a dummy clipboard.
       (catch Exception e (Clipboard. "headless"))))
```

**Comment by cnuernber** [comment]
This code will have to be in it's own namespace because you could also have a headless JDK in which case the awt toolkit isn't available.

**Comment by cnuernber** [comment]
This in now in [tech.v3.dataset.clipboard](https://techascent.github.io/tech.ml.dataset/tech.v3.dataset.clipboard.html).

Latest release with all the goodies is no longer beta (5.01).
