### ISSUE TITLE
clarify doc string of categorical->number

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#207]
From Zulip:

Maybe updating teh doc string of this function is fine:
categorical->number

To make it more clear , that the "categorical" in its name is not strongly related/restricted to columns "marked as categorical?"

But to say to the user:

tell me, which columns you consider "categorical" and
I will convert them to discrete, numeric columns
 6:17 PM
Because it would work with any column type, even float64, correct ?
or even Object ?

 6:18 PM
It simply does a mapping from all unique values to 0...n and keeps a table for mapping them back , correct ?

**Comment by cnuernber** [comment]
Updated in master
