### ISSUE TITLE
Lightweight empty columns

### ISSUE THREAD

**Issue by joinr** [techascent/tech.ml.dataset#21]
Implementing a left join example, realizing that having a flyweight empty column that projects in O(1) space an arbitrary range of missing values would be very useful for these kinds of joins.  Right now, we have to manually create a missing set (e.g. via new-column) full of all the entries.  Should be able to reify a set implementation that is just a countable thing that returns a range for reader/seq, and checks if indices are within an the range for containment.

Only tricky bit is promoting if we allow items to be added to the set.  Either coerce it to the full missing set as before, or work on a sparse scheme to allow "present" values, sort of like we use missing values for the column stuff.

**Comment by cnuernber** [comment]
If we want just a completely empty column then your suggested implementation makes sense.  We can have a const-reader that just returns the empty column value and a set implementation that returns all the indexes.  Is this useful?

**Comment by joinr** [comment]
Sounds useful.  Unsure what the semantics are if we later modify the empty column, e.g. by setting a value.  Something akin to an inverse of the Column implementation's "missing" set, e.g. a present set of sparse values maybe.  Either that, or make it a clean "if you add any values to this empty column, we'll coerce it to a real column, and incur the missing set index space hit".

**Comment by cnuernber** [comment]
I wonder if this moves to lightweight sparse columns where the assumption is the column only has a few actual values as opposed to a few missing values.  That would be a logical other column type for certain things.  It would be another column impl I would think but that isn't bad.  We already dropped the number of column impls from N->1 as compared to tablesaw.

**Comment by cnuernber** [comment]
I remember that core.matrix got into a *lot* of trouble right here.  Trying to automagically discern vectors from sparse vectors lead to a quite a bit of 'odd' and poor-performing behavior at the line between the two of them.  We hit that trouble almost immediately trying to use their sparse vectors for a client project.

**Comment by cnuernber** [comment]
tech.datatype as small bit of support for sparse vectors and tensors.  And that was extremely difficult to get right.

**Comment by joinr** [comment]
Yeah, regarding sparsity, not sure if the juice is worth the squeeze.  Then again, as more users start piling on (like wade) and extending the use cases, maybe it becomes more important.

It's an optimization at this point.

**Comment by joinr** [comment]
Maybe footnote it for now, get the joins testing and API solid, then revisit if necessary in the future as a performance feature.

**Comment by cnuernber** [comment]
Testing in general could use some major beefing up.  Do you have any suggestings for how to go about that?

The sort of one-off spot checks I do are useful for getting things going quick but, for instance, concat not dealing with missing columns kind of threw me.  It didn't go through the select pathway so I guess that is where it came in.

**Comment by joinr** [comment]
I'm trying to add some join tests from the ww3 data, as well as API calls for inner, left, right join that use join-by-column and provide a dataset->dataset interface.

About to open an issue about left-join not looking like I expect.  Thinking also of generating synthetic data with specs and generative testing stuff.  could pop onto zulip instead of me spamming issues if you'd like too.

**Comment by joinr** [comment]
Other option is to replicate some of the nominal DB tests from say a pre-baked fake dataset (I started with WW3 for instance), and then just build tests from that for hardening (or replicate their examples).

**Comment by cnuernber** [comment]
Either works.  We are probably too chatty for issues ;-).  But any actual bug (like left join not looking like you expect) seems to me to be a real issue.  I mean, or a PR with a set of failing test cases.

My impression of left outer join is just to make a sub-table of the indexes on the left that didn't match.  This didn't pass your test as I think the expectation may be to have the full join table along with missing values for the things that didn't match.

**Comment by joinr** [comment]
Yeah, my expectation from database-land (not that I'm a DB guru or anything) is that you'd have the full table with empty fields, hence the empty column direction I went.

**Comment by joinr** [comment]
As it stands, your version discards empties...so other than maintaining the indices, there's nothing to realize e.g. no empty columns of populated data.  My perspective is lacking on whether this is a good or bad thing; just an observation.

**Comment by joinr** [comment]
For Wade's case, it seems like it would be incorrect (e.g. the fields that didn't match in a left-join "Should" be present for later joins or something), which means you'd need to have empty column entries, which also means those columns may become non-empty on a later join.  I also didn't get what Wade's dataset / use-case was for the multiple joins though...only that he was missing data that got pruned.

**Comment by joinr** [comment]
You keep track of the indices though, so there's a path to get at what he was trying.

**Comment by cnuernber** [comment]
The indices are the get-out-of-jail card when shit isn't what you expected it to be.

**Comment by joinr** [comment]
If the semantics of the library are to not provide a reified view of empty entries, but optionally expose the indices, then an empty column probably doesn't make sense.

**Comment by cnuernber** [comment]
Let's keep it there.  Indexes are exposed and the actual left join table with values is returned.  

Given those expectations then does the library pass the new join tests?

**Comment by joinr** [comment]
I think so.  Looking at right and inner joins (same dataset).  I think it's good.  Will publish a p/r with suggested additions.

**Comment by joinr** [comment]
left-join test looks wrong.  It's not bringing in columns from rhs.

**Comment by cnuernber** [comment]
left outer join is the items in the left hand side that don't have representation in the right hand side by my understanding.  Isn't that what we talked about above?  I may be lost :-).

**Comment by cnuernber** [comment]
Well, I guess not in DB terms.  Maybe better nomenclature.

**Comment by joinr** [comment]
migrated to #26
