### ISSUE TITLE
confusing behaviour on dataset creation if columns have different length

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#220]
Doing this:
```clojure
(ds/->dataset {:text ["a" "b"]
                 :score "none"]})
```

by mistake, results in this dataset
```
 => _unnamed [4 2]:
      |   :text | :score |
      |---------|--------|
      |       a |      n |
      |       b |      o |
      |         |      n |
      |         |      e |)
  ```
  So it took the single string as  a sequence.
  
  It took me 30  minutes to debug this...
  so maybe there is something we could do.

**Comment by behrica** [comment]
Just for reference, pandas fails in both cases:

pd.DataFrame([1,2,3],"hello")
pd.DataFrame([1,2,3],["hello"])

**Comment by cnuernber** [comment]
I thought I had failing behavior earlier and @genmeblog had an R example where the dataset just took the longest column and produced empty values for the columns that didn't make it.

I am totally fine making this an error - I think that is better for the long run.

**Comment by genmeblog** [comment]
afair R (dplyr) does this way. TC brings more stuff around uneven columns (you can cycle, single value is propagated, etc.). 
I opt for warning an user rather than throwing an exception.

**Comment by behrica** [comment]
Maybe we error out only if a single String is passed as a "column".
If it is a seq, we could maybe recycle.
(or leave as is)

**Comment by genmeblog** [comment]
This is how it works in TC:

```clojure
(api/dataset {:text ["a" "b"]
              :score "none"})
;; => _unnamed [2 2]:
;;    |   :text |  :score |
;;    |---------|---------|
;;    |       a |    none |
;;    |       b |    none |

(api/dataset {:text ["a" "b"]
              :score ["none"]})
;; => _unnamed [2 2]:
;;    |   :text |  :score |
;;    |---------|---------|
;;    |       a |    none |
;;    |       b |         |

(api/dataset {:text ["a" "b"]
              :score (seq "none")})
;; => _unnamed [4 2]:
;;    |   :text | :score |
;;    |---------|--------|
;;    |       a |      n |
;;    |       b |      o |
;;    |         |      n |
;;    |         |      e |
```

**Comment by behrica** [comment]
Yeah, I did not realise that TC and dataset a differ that much in dataset creation.

TC seams to me "more logical",
so maybe we could even close here, saying that TC is the user friendly way to go.

**Comment by cnuernber** [comment]
This is a good issue and should be fixed at a low level.  Strings are treated as scalars throughout the datatype and dataset libraries and characters don't exist as a meaningful datatype, you have `:uint16` and `:uint32`.  The behavior that would be consistent would be for the scalar to be smeared as if you had passed a constant or done `(assoc ds :a 1)` which produces an `:int64` column of constant 1's.

So that is one thing I can take from this.  Please leave it open for now :-).
