### ISSUE TITLE
select-columns returns `nil` on empty dataset

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#225]
```clojure
(ds/select-columns (ds/->dataset {}) [])
;; => nil
```

In above case I would expect to get just empty dataset. 

original issue: https://github.com/scicloj/tablecloth/issues/36

**Comment by cnuernber** [comment]
deal.  Good issue -- null punning here is not a great idea.  Potentially a `(dataset ds)` function that will return nil on empty dataset analogous to seq.
