### ISSUE TITLE
Some spreadsheet numeric cells are dates not floats

### ISSUE THREAD

**Issue by otfrom** [techascent/tech.ml.dataset#233]
`tech.v3.dataset.io.spreadsheet/sheet->dataset` handles multiple types, but sometimes turns date formatted cells into floats. There is a quick java example showing how to handle it here: https://poi.apache.org/components/spreadsheet/quick-guide.html#CellContents

I think the `:float64` probably just needs an if statement to handle the 2 types.

**Comment by cnuernber** [comment]
@DavidVujic - I think this is relevant to your interests - 

Release 5.22 now includes auto-inferring of local date types in xlsx spreadsheets if you use `tech.v3.libs.poi/workbook->datasets`.  This means if you have code fixing this issue I probably broke your stuff - be wary if you upgrade.

**Comment by DavidVujic** [comment]
Thank you for the heads up!

**Comment by otfrom** [comment]
Thx for the fix!
