### ISSUE TITLE
wrong docs for parser function

### ISSUE THREAD

**Issue by ozimos** [techascent/tech.ml.dataset#234]
returning :tech.ml.dataset.parser/missing or :tech.ml.dataset.parser/parse-failure as stated [here](https://techascent.github.io/tech.ml.dataset/tech.v3.dataset.html) in the docs for ->dataset :parser-fn option causes an exception. This is solved by returning nil

**Comment by cnuernber** [comment]
I see, thanks for the issue!  I will follow up soon.

**Comment by cnuernber** [comment]
I wrote a quick test showing how to use the custom parse method for a particular column - https://github.com/techascent/tech.ml.dataset/blob/master/test/tech/v3/dataset/parse_test.clj#L411.

Can you post an example of exactly what you did?  The test I wrote passes.

**Comment by ozimos** [comment]
I tried :tech.ml.dataset.parser/missing and :tech.ml.dataset.parser/parse-failure. Your tests use :tech.ml.dataset.parse/missing and :tech.ml.dataset.parse/parse-failure. The namespace on the keywords are not the same :tech.ml.dataset.parser vs :tech.ml.dataset.parse. The docs should be updated

**Comment by cnuernber** [comment]
Got it, agreed, thanks for your patience with this issue!

**Comment by cnuernber** [comment]
@ozimos - For the `6.00` branch I changed the keywords to be namespaced in `tech.v3.dataset` namespace as opposed to `tech.ml.dataset.parse` namespace so you can use the same `ds` alias and don't need a new namespace.  Docs have been updated :-).

This was an external interface change that pertains to the above discussion!

**Comment by ozimos** [comment]
That makes more sense. I was wondering about that. And the updated namespace is less susceptible to typos
