### ISSUE TITLE
replace-missing additional case

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#237]
I think that another case for missing manipulation can be introduced.

```
(tc/replace-missing foo :b (fn [{:keys [a b]}] (or b (inc a))))
```

For every missing value provided `fn` is called with whole row and result is a value for replacement.
When `fn` return `nil` - the missing value stays missing.

**Comment by cnuernber** [comment]
Yes, something like this.  This matches the use case that we saw earlier:
```clojure
(sequence
         (map (fn [{:keys [academic-year-1 academic-year-2 calendar-year id] :as transition}]
                (cond-> transition
                  (nil? academic-year-1)
                  (assoc :academic-year-1 (dec academic-year-2))
                  (nil? academic-year-2)
                  (assoc :academic-year-2 (inc academic-year-1))
                  (and (nil? calendar-year) (:right.calendar-year transition))
                  (assoc :calendar-year (:right.calendar-year transition))
                  (and (nil? id))
                  (assoc :id (:right.id transition)))))
```

That really is a much of replace-missing statements where you want to substitute key for another.

**Comment by cnuernber** [comment]
Well, assuming that the datatset's missing set accurately reflects where the nil values are - which in the 6.00 branch they should.

**Comment by cnuernber** [comment]
with the `6.XX` branch the above code becomes a series of dataset column-map pathways.  That is a solid amount more efficient I think and just as clear:

```clojure
(-> ds
     (ds/column-map :academic-year-1 
                                (fn [academic-year-1 academic-year-2] (or academic-year-1 (dec (long academic-year-2)))
                                [:academic-year-1 :academic-year-2]))
    ...) 
```

And the resulting column will get its datatype and missing information inferred which should be identical to the above pathway.

**Comment by cnuernber** [comment]
With [column-map-m](https://techascent.github.io/tech.ml.dataset/tech.v3.dataset.html#var-column-map-m) that becomes:

```clojure
(-> ds 
          (ds/column-map-m :academic-year-1 [:academic-year-1 :academic-year-2]
                           (or academic-year-1 (dec academic-year-2))))
```

**Comment by cnuernber** [comment]
hmm...periods in variable names...That isn't guaranteed to work; I think that breaks some Clojure assumptions.

**Comment by cnuernber** [comment]
Fixed - beta-4 :-).  Now docs have [example](https://techascent.github.io/tech.ml.dataset/tech.v3.dataset.html#var-column-map-m).

**Comment by cnuernber** [comment]
Closing this as I believe that column-map can be efficiently used to perform this type of replace missing.
