### ISSUE TITLE
Poor performance of ds/remove-columns vs. ds/select-columns

### ISSUE THREAD

**Issue by alex314159** [techascent/tech.ml.dataset#240]
Hi Chris,

It seems that `ds/remove-columns` is very slow and uses a lot of memory, in particular vs. `ds/select-columns`. Here's a not so contrived example of a dataset I'm working with:

```
(def a (ds/->dataset (repeat 250 (into {} (for [i (range 60000)] [(str "c" i) 0])))))
(def b (ds/select-columns a (into [] (for [i (range 40000)] (str "c" i)))))  ; this is reasonably quick
(def c (ds/remove-columns a (into [] (for [i (range 40000 60000)] (str "c" i))))) ; extremely slow
```

Is there any gotcha there? Is select-columns just a view with the cost to be paid in later calculations?

Thanks a lot,

**Comment by cnuernber** [comment]
Interesting test.  They should be equivalent but of course they are not:

https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/v3/dataset/base.clj#L141

reduce is creating a new dataset per removed column.  It is the wrong primitive to use there.

**Comment by alex314159** [comment]
thank you for fixing so quickly!!
