### ISSUE TITLE
support for reading zipped csv files from input stream ?

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#247]
I tried to read from a file stream pointing to a zipped csv file and could not get it working:

```
(ds/->dataset
 (clojure.java.io/input-stream (clojure.java.io/resource "data/diabetes_data.csv.gz")) {:file-type :csv :gzipped? true} )
```
It creates a dataset which kind of binary content, so it looks like the unzipping does not take place.

Is it supposed to work ?

**Comment by cnuernber** [comment]
Yes, gzipped files are supposed to work both reading and writing.  This is an issue.
