### ISSUE TITLE
Serialize tech.v3.dataset.impl.column.Column

### ISSUE THREAD

**Issue by zalky** [techascent/tech.ml.dataset#252]
It would be nice to be able to serialize an individual column. The motivation is that rather than serializing an entire dataset, it is sometimes preferable to serialize a diff between two datasets, which can resolve to an individual column object (`tech.v3.dataset.impl.column.Column`).

I don't know what the canonical solution would be, but I was able to extend it in our own project just borrowing the pieces in `tech.v3.dataset/data->dataset` and `tech.v3.dataset/dataset->data`, then something like:

```clj
(nippy/extend-freeze Column :tech.v3.datset.column/column
  [col out]
  (nippy/-freeze-without-meta! (col->data col) out))

(nippy/extend-thaw :tech.v3.datset.column/column
  [in]
  (column/new-column (data->col (nippy/thaw-from-in! in))))
```

**Comment by cnuernber** [comment]
There is also an analogy here to sharing an arrow column with a python process.  Good idea!

**Comment by zalky** [comment]
Superb! Thanks for sorting this out so quick!
