### ISSUE TITLE
app shutdown slow

### ISSUE THREAD

**Issue by awb99** [techascent/tech.ml.dataset#253]
I just ran a very simple clojure app, using tech.ml.dataset and tech.ml.io using nippy serialization.
When the app batch finishes, it takes 7 seconds until the app returns to the os.
Could this be some kind of logger configuration that stops quick shutdown?
Thanks.

**Comment by cnuernber** [comment]
I think it is the agent pool.  See clojure.core/shutdown-agents!.   Pmap uses this pool.

**Comment by cnuernber** [comment]
Closing as this is an issue with pmap and the clojure core libraries.
