### ISSUE TITLE
Should left-join and right-join return all fields?

### ISSUE THREAD

**Issue by joinr** [techascent/tech.ml.dataset#26]
referenced in pull request #25 .  I think the behavior for left and right joins would be to include the fields from both lhs and rhs.  The difference between the two would be in the missing fields and missing values on either the lhs fields or rhs fields in the resulting joined table.  Uncertain if - given the design only returns indices - this is a pedantic difference.  Any join operation will return all the fields of both tables then.  Tests predicates in #25 can be altered trivially if I'm mistaken.

**Comment by joinr** [comment]
Given:

lhs = 
```
ID | Name | Age | Home
-- | -- | -- | --
1 | Bilbo | 400 | Shire
2 | Kirk | 42 | Enterprise
3 | Voltron | 99999 | Earth
```
rhs = 
```
ID | Genre | Medium
-- | -- | --
1 | Fantasy | Multiple
2 | SciFi | Multiple
50 | Random | TV
```

`(left-join "ID" lhs rhs)` =

```
ID | Name | Age | Home | Genre | Medium
-- | -- | -- | -- | -- | --
1 | Bilbo | 400 | Shire | Fantasy | Multiple
2 | Kirk | 42 | Enterprise | SciFi | Multiple
3 | Voltron | 99999 | Earth | null | null
```

`(right-join "ID" lhs rhs)` =
```
ID | Name | Age | Home | Genre | Medium
-- | -- | -- | -- | -- | --
1 | Bilbo | 400 | Shire | Fantasy | Multiple
2 | Kirk | 42 | Enterprise | SciFi | Multiple
50 | null | null | null | Random | TV
```

`(inner-join "ID" lhs rhs)`  = 
```
ID | Name | Age | Home | Genre | Medium
1 | Bilbo | 400 | Shire | Fantasy | Multiple
2 | Kirk | 42 | Enterprise | SciFi | Multiple
```

I think.  Right now, the behavior for the left/right joins does not pull in the columns from the other table.

**Comment by cnuernber** [comment]
I vote we rename the join to hash-join (we may want sort-join) and implement exactly  the above based on the output of hthe existing ash join.

**Comment by cnuernber** [comment]
Not sure the best technical way to pull that one off yet.  The appropriate columnwise representation I think is tough when half or all are empty values.  In this case the missing set is a range like you have done and HashSet isn't that.

**Comment by cnuernber** [comment]
Great issue.

**Comment by joinr** [comment]
I don't think the empty value semantics are as important here specifically (although it'd be useful to think on).

Rather, the key issue is that, right now, in the implementation, we don't end up pulling in the fields from the other table...e.g.


`(left-join   "ID" lhs rhs)` currently would yield:

ID | Name | Age | Home
-- | -- | -- | --
1 | Bilbo | 400 | Shire
2 | Kirk | 42 | Enterprise

and `(right-join "ID" lhs rhs)` yields:

ID | Genre | Medium
-- | -- | --
1 | Fantasy | Multiple
2 | SciFi | Multiple

I would expect something like `inner-join`, 

ID | Name | Age | Home | Genre | Medium
-- | -- | -- | -- | -- | --
1 | Bilbo | 400 | Shire | Fantasy | Multiple
2 | Kirk | 42 | Enterprise | SciFi | Multiple


with the current semantics for either right/left, except you'd get additional 
indices depending on the invocation.  Without adding any missing values or empty columns,
the join-table is effectively identical between both (or should be), with additional info for the missing indices.

**Comment by joinr** [comment]
I replicated your call from the join-test ns, where you unpack the :lhs-outer-join from the join call, and that's your left-join.  Looks like this is wrong too (or at least my interpretation of it was), since in the above datasets.  After revisiting the implementation, I realize it was my mistake to project some meaning where it shouldn't have been.  Let me see if I can revamp this to make sure my implementation of left/right join isn't at fault.

**Comment by joinr** [comment]
Yeah, I was mistaken on the implementation side, shouldn't have just ganked :lhs-outer-join.  without empty column entries, left/right-join don't make sense.  They are effectively `inner-join` with metadata.

**Comment by joinr** [comment]
So, the "real answer" to my question is I think "yes, all fields should be returned" but "join already does that!"  If we want something akin to the semantics of left-join/right-join as above, we either implement empty stuff, or we pack along the indices as metadata (despite the join-table looking identical between inner, left, right joins...).

**Comment by cnuernber** [comment]
Makes sense.  So let's punt for now :-).

Maybe columns should!   The only rule is setting metadata makes a new column.
