### ISSUE TITLE
Positional naming/renaming of dataset columns

### ISSUE THREAD

**Issue by respatialized** [techascent/tech.ml.dataset#262]
I was working with a dataset that had repeated column names and the existing map-based methods made it tricky to rename the columns to avoid the duplicates. I was thinking that positional assignment of column names might be both a solution to this particular problem and a more generally useful capability for `tech.ml.dataset`. On [Zulip](https://clojurians.zulipchat.com/#narrow/stream/151924-data-science/topic/Tablecloth.3A.20rename.20duplicate.20columns.3F), it was suggested that I open an issue here about this. 

If possible, I'd like to work up a PR for this. It could either be a new function `name-columns`, or an extension to `rename-columns` that behaves differently if a vector is passed in. I have no opinion one way or another about which is preferable.

**Comment by cnuernber** [comment]
Both are good options - I would like to stick with `rename-columns` to avoid another symbol.  If we go with a vector approach the only requirement I see is that the vector must be complete - it must have a name for every column.  This is not currently true for the map approach.

**Comment by cnuernber** [comment]
Fixed by #264
