### ISSUE TITLE
Consider adding features to print/display at a dataset at the editor/repl similar to those found in other ecosystems such as Python's Pandas

### ISSUE THREAD

**Issue by ahuggins0006** [techascent/tech.ml.dataset#266]
For example, truncating the center portion of a dataset that is too large to fit into current view while also giving a user a good preview of the data. Also consider adding more options for printing the datasets such as printing nested data or providing color.

**Comment by cnuernber** [comment]
Good ideas.  Currently we do truncate to the first n rows but I agree lots of times it is far more useful to see first/last N.

**Comment by cnuernber** [comment]
Also, nested data/datasets do in fact print.

**Comment by cnuernber** [comment]
See update docs: https://techascent.github.io/tech.ml.dataset/tech.v3.dataset.print.html
