### ISSUE TITLE
`replace-missing`  removes sometimes column  metadata

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#274]
see here : https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/.60replace-missing.60.20.20removes.20sometimes.20column.20.20metadata

**Comment by behrica** [comment]
Could it be that there are similar problems in other places.
Each time a column is changed by a function which is using `new-column` ?

**Comment by behrica** [comment]
https://github.com/techascent/tech.ml.dataset/blob/717383ffe358f17c5b924edc685a3a3ed59a2f4d/src/tech/v3/dataset/math.clj#L203  ?

**Comment by behrica** [comment]
Probably it is correct to say, that a TMD function should not "touch" any column metadata it is not directly concerned with.
(especially preserving all existing column metadata)

**Comment by cnuernber** [comment]
Yes I agree.

**Comment by cnuernber** [comment]
Fixed in latest.
