### ISSUE TITLE
Reading input-stream: changed behaviour between 6.027 and 6.035

### ISSUE THREAD

**Issue by alex314159** [techascent/tech.ml.dataset#279]
Hi Chris,

hope you are well! Just wanted to note a small behaviour change when reading input-streams between 6.027 and 6.035

```
;6.027 behaviour
(tech.v3.dataset.io/data->dataset (io/input-stream (.getBytes "date,a,b\n2020-03-05,3,5\n2021-03-08,5,9")) {:file-type :csv :parser-fn {"date" [:local-date "yyyy-MM-dd"]}})
=> _unnamed [2 3]:

|       date | a | b |
|------------|--:|--:|
| 2020-03-05 | 3 | 5 |
| 2021-03-08 | 5 | 9 |

;6.035 behaviour
(tech.v3.dataset.io/data->dataset (io/input-stream (.getBytes "date,a,b\n2020-03-05,3,5\n2021-03-08,5,9")) {:file-type :csv :parser-fn {"date" [:local-date "yyyy-MM-dd"]}})
=> _unnamed [0 0]

;However, THIS WILL WORK if you include the separator:

(tech.v3.dataset.io/data->dataset (io/input-stream (.getBytes "date,a,b\n2020-03-05,3,5\n2021-03-08,5,9")) {:file-type :csv :separator "," :parser-fn {"date" [:local-date "yyyy-MM-dd"]}})
=> _unnamed [2 3]:

|       date | a | b |
|------------|--:|--:|
| 2020-03-05 | 3 | 5 |
| 2021-03-08 | 5 | 9 |


```

Might be worth a comment in the doc, or a warning if no separator is given.

Thank you,

**Comment by cnuernber** [comment]
Alex, thanks for the note!  Unfortunately univocity puts us between a rock and a hard place.  Passing in the separator will make other files fail...something we just found out and is exhibited in [this unit test](https://github.com/techascent/tech.ml.dataset/issues/275).  

Honestly univocity is slowly moving onto the shitlist and once there I will start investing in making a for of the vanilla clojure.data.csv - which is [extremely simple](https://github.com/clojure/data.csv/blob/master/src/main/clojure/clojure/data/csv.clj) - efficient enough to just use that.

Agreed a doc update and saving this as a perhaps commented out unit test is a good next step!

**Comment by alex314159** [comment]
thank you! Tricky indeed...

**Comment by cnuernber** [comment]
Closing for now.  This issue still exists but is unfixable due to interlocking underlying issues with univocity.
