### ISSUE TITLE
make tech.ml.dataset available as a Java API?

### ISSUE THREAD

**Issue by subes** [techascent/tech.ml.dataset#281]
As discussed here: https://github.com/cnuernber/dtype-next/issues/52#issuecomment-1016949834
It might be interesting to provide a high level API for tech.ml.dataset. The Java binding in dtype-next now makes it possible to integrate it, but I guess this can still be made easier.

**Comment by cnuernber** [comment]
Fixed as of version 6.054.

This was a bit of work but very rewarding.  There was actually a considerable amount of polish done and small upgrades to dtype-next to make this as pleasant as reasonably possible to use from Java.  It is extremely awkward to do this stuff from outside a repl context and the load times make edit/run cycles slow.  But the API is there and perhaps there are Java repl-type systems that won't need to restart a lot.

Java [API documentation](https://techascent.github.io/tech.ml.dataset/javadoc/index.html) and [sample](https://github.com/techascent/tech.ml.dataset/blob/master/java_test/java/jtest/TMDDemo.java).

I will be in touch soon about project.
