### ISSUE TITLE
commit b6f9f4e3eb051f66fd41ca00d91368e1bc7cb848 introduced backward incompatibility

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#295]
In `dataset.clj` before that commit,

the function `new-col` was re-exported twice, probably by mistake.
https://github.com/techascent/tech.ml.dataset/blob/fddeddcb96a041bfe36f380721370191355260b7/src/tech/v3/dataset.clj#L56
https://github.com/techascent/tech.ml.dataset/blob/fddeddcb96a041bfe36f380721370191355260b7/src/tech/v3/dataset.clj#L213

so the second one "won".

After the change, only the first one stayed, having a different arrity and probably doing something different as well.

So any code using `tech.ml.dataset.new-column` before b6f9f4e3eb051f66fd41ca00d91368e1bc7cb848 will stop compiling  
when moving to b6f9f4e3eb051f66fd41ca00d91368e1bc7cb848 + 1.
```
 :at [clojure.lang.Compiler$InvokeExpr eval Compiler.java 3711]}
  {:type clojure.lang.ArityException
   :message Wrong number of args (2) passed to: tech.v3.dataset/new-column
   :at [clojure.lang.AFn throwArity AFn.java 429]}]
````

As this is in the main namespace it might affect some people.

**Comment by cnuernber** [comment]
Great catch thanks a lot for tracking this down.
