### ISSUE TITLE
Parquet decimal type not implemented

### ISSUE THREAD

**Issue by chrysophylax** [techascent/tech.ml.dataset#296]
The type Decimal is missing from the parquet reader. 

I've done some testing and managed to get a reader now per https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/parsing.20parquet.20Decimal.20type.

A test file can be generated by using this Python3 code

```Python
import pyarrow.parquet as pq
import pyarrow as pa
d = {'name': ['sample1', 'sample2'], 'decimals': [ 3.4199, 1.2455] }
table = pa.Table.from_pydict(d)
table = table.set_column(1, 'decimals', table.column('decimals').cast(pa.decimal128(12,9)))
pq.write_table(table, 'decimaltable.parquet')
```

**Comment by cnuernber** [comment]
The included PR has a fix for this issue.
