### ISSUE TITLE
new empty column is set to boolean datatype

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#300]
```
(tech.v3.dataset.column/new-column :a [])
;; => #tech.v3.dataset.column<boolean>[0]
;;    :a
;;    []
```

Is there a way to force a datatype during creation of column?

**Comment by cnuernber** [comment]
Yes - use the map constructor form - or use empty container of target datatype - will have example forthcoming.

**Comment by cnuernber** [comment]
The only thing that will work is to create an empty container of the target datatype - 
```clojure
user> (require '[tech.v3.datatype :as dt])
nil
user> (ds/new-column :a (dt/make-reader :float32 0 nil))
#tech.v3.dataset.column<float32>[0]
:a
[]
```

**Comment by cnuernber** [comment]
Closing this for now.  This isn't clearly an issue - boolean is the root of the type hierarchy.
