### ISSUE TITLE
dataset key-fn option (new) unexpected behavior

### ISSUE THREAD

**Issue by alex314159** [techascent/tech.ml.dataset#311]
Hi Chris,

could be linked to #259

```
(ds/->dataset [{"a o" 1 "b o" 2} {"a o" 5 "b o" 3}] {:key-fn #(keyword (clojure.string/replace % " " "-"))})
=> _unnamed [2 2]:

| ::b-o | ::a-o |
|------:|------:|
|     2 |     1 |
|     3 |     5 |
```

See the double colon - I can't get simple keywords. This works ofc:

```
(ds/->dataset [{"a o" 1 "b o" 2} {"a o" 5 "b o" 3}] {:key-fn #(if (keyword? %) % (keyword (clojure.string/replace % " " "-")))})
=> _unnamed [2 2]:

| :b-o | :a-o |
|-----:|-----:|
|    2 |    1 |
|    3 |    5 |
```

completely unrelated but not worth an issue: the changelog.md file jumps from 6.080 to 8.081 (big figure change!)

Thank you!

**Comment by alex314159** [comment]
Reading in more details it's exactly same as #259, sorry for duplicate

**Comment by cnuernber** [comment]
No worries - yes duplicate but original is old and time to fix both.

**Comment by alex314159** [comment]
thank you!!
