### ISSUE TITLE
Concatenate nil to empty dataset returns nil

### ISSUE THREAD

**Issue by alex314159** [techascent/tech.ml.dataset#315]
Hi Chris,

Small edge case - usually `(ds/concat dataset nil)` returns the dataset, however if the starting dataset is empty it returns nil which can break pipelines. Is this desired behaviour?

Example:
```
(ds/drop-rows (ds/->dataset [{:a 1 :b 2}]) [0])
=> _unnamed [0 2]:

| :b | :a |
|---:|---:|

(ds/concat (ds/drop-rows (ds/->dataset [{:a 1 :b 2}]) [0]) nil)
=> nil    ; I would have expected same as above

```

Thanks!!

**Comment by cnuernber** [comment]
We don't want to break pipelines - I agree the with your suggestion of a better behavior.

**Comment by alex314159** [comment]
thank you!
