### ISSUE TITLE
Maybe preserve order with mapseq-reader?

### ISSUE THREAD

**Issue by joinr** [techascent/tech.ml.dataset#316]
referencing: 

https://clojurians.zulipchat.com/#narrow/stream/151924-data-science/topic/tech.2Eml.2Edataset/near/289439519

If we use a linked hashmap to store the column names for the FastStruct in tech.v3.dataset.readers/mapseq-reader, order is preserved at no cost (linear traversal/iteration of a linked list with amortized O(1) lookup, instead of using a sorted map that incurs balanced binary tree lookup costs).  I didn't look too deeply, but I assume the field for column names is semantically read-only (we're already using a hashmap...) after the FastStruct is instantiated, so this shouldn't impact correctness.

```clojure
(defn mapseq-reader
  "Return a reader that produces a map of column-name->column-value
  upon read."
  (^Buffer [dataset options]
   (let [colnamemap (LinkedHashMap.)  ;;<------Changed HERE
         _ (doseq [[c-name c-idx] (->> (ds-proto/columns dataset)
                                       (map (comp :name meta))
                                       (map-indexed #(vector %2 (int %1))))]
             (.put colnamemap c-name c-idx))
         colnamemap (Collections/unmodifiableMap colnamemap)
         copying? (get options :copying?)
         readers (r/value-reader dataset options)]

     (reify ObjectReader
       (lsize [rdr] (.lsize readers))
       (readObject [rdr idx]
         (let [data (readers idx)]
           (FastStruct. colnamemap (if (instance? ListPersistentVector data)
                                     (.data ^ListPersistentVector data)
                                     data)))))))
  (^Buffer [dataset]
   (mapseq-reader dataset nil)))
```

The only downside I can think of is enabling people to assume ordering is there for mapseqs and getting into trouble elsewhere.  It could be an option, but to me it seems like if we are providing an efficient indexed struct-like view over the dataset and we know the ordering, that could be guaranteed in the contract.  I haven't done any performance comparisons, although I think it would be identical for lookups.

**Comment by joinr** [comment]
It looks like there is an assumption in FastStruct.java that the slots would be a HashMap as well, which impacts dissoc operations since they create a new HashMap with the underlying fields removed.  Not bad, but at least one other place to modify/thread the ordering semantics.  It also looks like assoc will push to an external unordered persistent map (akin to clojure record's implementation), so then ordering gets odd there.  So no guarantees of ordering if you assoc new keys onto the map.  That could get confusing.

**Comment by cnuernber** [comment]
This makes total sense to me - agreed it should be a linked hash map.
