### ISSUE TITLE
Option to specify file encoding via ->dataset

### ISSUE THREAD

**Issue by hjrnunes** [techascent/tech.ml.dataset#320]
Only way to do this AFAIK is via `tech.v3.dataset.io.univocity/csv->dataset`, which can take a `Reader`.

**Comment by cnuernber** [comment]
I did a partial fix.  You can now supply a reader to ->dataset.  An explicit encoding option is another pathway that is more involved so I have decided not to do this on first try.

**Comment by cnuernber** [comment]
Partially fixed.  Closing for now, people can now provide readers constructed however they like.
