### ISSUE TITLE
ds/column-map with nil issue between 6.093 and 6.096

### ISSUE THREAD

**Issue by alex314159** [techascent/tech.ml.dataset#321]
Hi Chris,

the following works in 6.093 but fails in 6.096 - is this a regression, or how to achieve desired behaviours (e.g. nils in column c where either column a or b is nil):

```
(def x (ds/->dataset [{:a 3 :b 4} {:a 7 :b nil} {:a nil :b 5}]))
=> #'jasmine.quantscreen.svm/x
x
=> _unnamed [3 2]:

| :b | :a |
|---:|---:|
|  4 |  3 |
|    |  7 |
|  5 |    |

(ds/column-map x :c #(- %1 %2) {:datatype :float64 :missing-fn ds-col/union-missing-sets} [:a :b])
Execution error (NullPointerException) at jasmine.quantscreen.svm/eval56974$fn (form-init13710720466686580742.clj:1).
Cannot invoke "Object.getClass()" because "x" is null
```

Thanks!

**Comment by cnuernber** [comment]
Right - we were seeing too many sometimes serious performance issues with leaving the column-map operation lazy so I made it immediate and parallel.  The side effect of this was that missing values would make it through to the map function.  I think that if you are providing a missing set or missing set function like you have then we can avoid this crash specifically with a bit more engineering.

**Comment by cnuernber** [comment]
In the meantime having your function check for nil would avoid this but I understand that isn't as ideal as it was.

**Comment by alex314159** [comment]
Right, I see, thanks for the quick reply. Performance is important of course but permissive nil handling is also very important for real life datasets IMHO, and the :missing-fn parameter was an elegant way to deal with it - would be great to have a way to not fail on nil, even at the expense of performance.

**Comment by cnuernber** [comment]
Agreed - working on it presently

**Comment by cnuernber** [comment]
6.097 should fix this issue.

**Comment by alex314159** [comment]
oh wow - thank you!!!
