### ISSUE TITLE
requiring [tech.v3.libs.arrow :as arrow] delays JVM shudown

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#325]
unless (shutdown-agents) is used

Caused by
https://github.com/techascent/tech.ml.dataset/blob/f86550c7e3f823e812d5f5f652a3927f90590ee1/src/tech/v3/libs/arrow.clj#L240
?

**Comment by cnuernber** [comment]
I was unable to reproduce this - https://github.com/techascent/tech.ml.dataset/tree/master/ubertest - compiles and exits clean without shutdown agents.  So it is isn't the require itself.

**Comment by cnuernber** [comment]
I spoke too soon.  Writing a very simple arrow file did produce the hang on shutdown.

**Comment by cnuernber** [comment]
Simply creating a dataset produced the hang - no arrow require required.

**Comment by behrica** [comment]
Playing a bit, and requiring "tablecloth" reproduces it as well

```
(ns clean
  (:require 
   ;; [clojure.string :as str]
   ;; [tech.v3.libs.arrow :as arrow]
   ;; [tech.v3.dataset]
   [tablecloth.api]))
  ```
  
  but not requiring arrow **alone**, indeed.

**Comment by cnuernber** [comment]
I am seeing calls to ->dataset with either a mapseq or a map of columns produces the hang - potentially tablecloth makes and empty dataset or something like that.

**Comment by cnuernber** [comment]
Any use of pmap, be it clojure.core/pmap or claypool pmap (called from dtype.parallel-for/pmap) causes agent issues.  That is very annoying and I did not expect that.

**Comment by cnuernber** [comment]
Yes

**Comment by genmeblog** [comment]
(replaced in `tablecloth` as well)
