### ISSUE TITLE
Sequence of integers is coerced to float64

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#34]
Is it proper behaviour?

```clj
(first (ds/name-values-seq->dataset {:t (repeatedly 10 #(rand-nth [1 2 3 4]))}))
;; => #tech.ml.dataset.column<float64>[10]
:t
[1.000, 3.000, 4.000, 3.000, 4.000, 4.000, 1.000, 2.000, 1.000, 2.000, ]
```

**Comment by cnuernber** [comment]
Good question, seems longs would be more appropriate here.  

If you wanted to force it you could create an primitive array of a given type.  Potentially the algorithm also for scanning data coming from sequences could be improved to use the same pathways as mapseqs or csv parsing.  This pathway has received the least amount of attention/testing/consideration.

**Comment by genmeblog** [comment]
Yep, longs are ok, behaviour shoud be the same regardless input or ds creation method.

```clojure
(first (ds/->dataset [{:a 1} {:a 2}]))
;; => #tech.ml.dataset.column<int64>[2]
:a
[1, 2, ]
```

Thanks for primitive array advice.

**Comment by genmeblog** [comment]
Looks like column case shows the same problem

```clojure
(col/new-column :abc [1 2 3 4])
;; => #tech.ml.dataset.column<float64>[4]
;;    :abc
;;    [1.000, 2.000, 3.000, 4.000, ]
```

**Comment by cnuernber** [comment]
reopening :-).

**Comment by cnuernber** [comment]
You get an object column now.  This to me makes sense when an object-datatype reader is passed in:

```clojure
tech.ml.dataset-test> (col/new-column :abc [1 2 3 4])
#tech.ml.dataset.column<object>[4]
:abc
[1, 2, 3, 4, ]
```

Closing again :-)
