### ISSUE TITLE
math/correlation-table always uses pearson correlation type

### ISSUE THREAD

**Issue by Menthalion** [techascent/tech.ml.dataset#340]
`correlation-type (or :pearson correlation-type)` always returns :pearson, should be `correlation-type (or correlation-type :pearson)`

**Comment by harold** [comment]
The relevant line: https://github.com/techascent/tech.ml.dataset/blob/9efd3aeaa47bfe208fba435259668a6f777dbd56/src/tech/v3/dataset/math.clj#L84

**Comment by cnuernber** [comment]
Unreleased as of yet.
