### ISSUE TITLE
left-join failing on dates in 7.000-beta-10 compared to v6

### ISSUE THREAD

**Issue by alex314159** [techascent/tech.ml.dataset#341]
Hi Chris,

Testing 7 beta. The following code fails:

```
(tech.v3.dataset.join/left-join
:a 
(ds/->dataset [{:a (LocalDate/of 2022 12 28) :b 3} {:a (LocalDate/of 2022 12 30) :b 4} {:a (LocalDate/of 2022 12 20) :b 4}])
(ds/->dataset [{:a (LocalDate/of 2022 12 20) :c 5} {:a (LocalDate/of 2022 10 20) :c 6} {:a (LocalDate/of 2022 11 20) :c 7}]))

Execution error (ClassCastException) at (REPL:1).
null
```

`right-join` fails too. An `inner-join` will work as expected. The `left-join` was working with v6. Note this is specific to dates, if `:a` was a column of integers it still works as expected.

Thank you!

**Comment by cnuernber** [comment]
Hmm - sorry about that, will get that tested and fix :-).

**Comment by alex314159** [comment]
so fast, thanks!!
