### ISSUE TITLE
tech.v3.libs.nettoolkit

### ISSUE THREAD

**Issue by harold** [techascent/tech.ml.dataset#344]
https://github.com/techascent/tech.ml.dataset/blob/7409ef595fe86e22c2fd05dd5f5131fe4f7e470e/src/tech/v3/libs/nettoolkit.clj#L2

This ns requires http-kit, but afaict http-kit is not included in this project.

I also don't see anyone that include this ns (`tech.v3.libs.nettoolkit`).

Not urgent, obviously, but what's this ns about?

it produces some stacktrace during docs build:

```
Could not generate clojure documentation for tech.v3.libs.nettoolkit - root cause: clojure.lang.Compiler$CompilerException Syntax error macroexpanding at (tech/v3/libs/nettoolkit.clj:1:1).
Syntax error macroexpanding at (tech/v3/libs/nettoolkit.clj:1:1).
	at clojure.lang.Compiler.load(Compiler.java:7665)
...
Caused by: java.io.FileNotFoundException: Could not locate org/httpkit/client__init.class, org/httpkit/client.clj or org/httpkit/client.cljc on classpath.
	at clojure.lang.RT.load(RT.java:462)
...
```

**Comment by cnuernber** [comment]
It was binding to nettookit which gives you geocoding of addresses - It is useful code but it is in source control - I think I should remove it from the project.

**Comment by cnuernber** [comment]
Baleeted

**Comment by harold** [comment]
(:
