### ISSUE TITLE
do we have dot product ?

### ISSUE THREAD

**Issue by usametov** [techascent/tech.ml.dataset#359]
Hi, you mentioned once in one of the releases that this lib has an implementation of dot-product for vectors and matrices. But I could not find it in documentation . Could you, please, add index for that? 
Sorry for bothering.

**Comment by usametov** [comment]
I saw your comment about cosine similarity here:
https://github.com/techascent/tech.ml.dataset/issues/102#issuecomment-653772295

And, I found this doc:
https://github.com/techascent/tech.datatype/blob/master/docs/01-operations.md

This should be enough for now. Thanks

**Comment by harold** [comment]
Indeed!

```clj
> (tech.v3.datatype.functional/dot-product [1 2 3] [4 5 6])
32.0
```

**Comment by harold** [comment]
Also, without the lib (in Clojure):

```clj
> (reduce + (map * [1 2 3] [4 5 6]))
32
```

This, of course, behaves differently in terms of types and performance, but may also be useful in some cases.
