### ISSUE TITLE
typo in arrow dependencies

### ISSUE THREAD

**Issue by bensu** [techascent/tech.ml.dataset#365]
Thank you for working in this project!

`[com.cnuernber "1.000"]` in the [arrow documentation page](https://techascent.github.io/tech.ml.dataset/tech.v3.libs.arrow.html) should probably be `[com.cnuernber/jarrow "1.000"]`:

```diff
  [org.apache.arrow/arrow-vector "6.0.0"]
- [com.cnuernber "1.000"]
+ [com.cnuernber/jarrow "1.000"]
  [org.apache.commons/commons-compress "1.21"]

  ;;Compression codecs
  [org.lz4/lz4-java "1.8.0"]
  ;;Required for decompressing lz4 streams with dependent blocks.
  [net.java.dev.jna/jna "5.10.0"]
  [com.github.luben/zstd-jni "1.5.4-1"]
```

Using `[com.cnuernber "1.000"]`  results in an error when the build tools (`lein` in my case) try to resolve the dependency.

**Comment by cnuernber** [comment]
100% correct - thanks for report!
