### ISSUE TITLE
sorting by columns with given order

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#37]
It would be great to have possibility to sort dataset by columns with given order. It's fairly easy to sort by columns with names as keywords ordering ascending:

```clojure
(->> (ds/->dataset [{:a 1 :b 2} {:a 11 :b -2} {:a 1 :b -1}])
     (ds/sort-by (juxt :a :b)))
;; => _unnamed [3 2]:
;;    | :a | :b |
;;    |----+----|
;;    |  1 | -1 |
;;    |  1 |  2 |
;;    | 11 | -2 |
```

But things are getting more complicated when:

- names are not keywords (custom field selector needs to be written)
- ordering is descending (custom comparator needs to be written)

I think enhancement should add `sort-by-columns` with the same arguments as `sort-by-column`. Also `compare-fn` can be: function (as is now) or seq of order, one of `:asc` and `:desc`.

Above example (imagined):

```clojure
(->> (ds/->dataset [{:a 1 :b 2} {:a 11 :b -2} {:a 1 :b -1}])
     (ds/sort-by-columns [:a :b] [:asc :desc]))
;; => _unnamed [3 2]:
;;    | :a | :b |
;;    |----+----|
;;    |  1 |  2 |
;;    |  1 | -1 |
;;    | 11 | -2 |
```

**Comment by genmeblog** [comment]
My custom solution, probably not efficient:

```clojure
(defn asc-desc-comparator
  [orders]
  (if (every? #(= % :asc) orders)
    compare
    (let [mults (map #(if (= % :asc) 1 -1) orders)]
      (fn [v1 v2]
        (reduce (fn [_ [a b mult]]
                  (let [c (compare a b)]
                    (if-not (zero? c)
                      (reduced (* mult c))
                      c))) 0 (map vector v1 v2 mults))))))

(defn sort-by-columns-with-orders
  ([cols ds]
   (sort-by-columns-with-orders cols (repeat (count cols) :asc) ds))
  ([cols orders ds]
   (let [sel (apply juxt (map #(fn [ds] (get ds %)) cols))
         comp-fn (asc-desc-comparator orders)]
     (ds/sort-by sel comp-fn ds))))


(->> (ds/->dataset [{:a 1 :b 2} {:a 11 :b -2} {:a 1 :b -1}])
     (sort-by-columns-with-orders [:a :b]))
;; => _unnamed [3 2]:
;;    | :a | :b |
;;    |----+----|
;;    |  1 | -1 |
;;    |  1 |  2 |
;;    | 11 | -2 |

(->> (ds/->dataset [{:a 1 :b 2} {:a 11 :b -2} {:a 1 :b -1}])
     (sort-by-columns-with-orders [:a :b] [:asc :desc]))
;; => _unnamed [3 2]:
;;    | :a | :b |
;;    |----+----|
;;    |  1 |  2 |
;;    |  1 | -1 |
;;    | 11 | -2 |

(->> (ds/->dataset [{:a 1 :b 2} {:a 11 :b -2} {:a 1 :b -1}])
     (sort-by-columns-with-orders [:a :b] [:desc :desc]))
;; => _unnamed [3 2]:
;;    | :a | :b |
;;    |----+----|
;;    | 11 | -2 |
;;    |  1 |  2 |
;;    |  1 | -1 |
```

**Comment by cnuernber** [comment]
This also extends to filter-by-columns if we can make the filter operator a function that takes arguments in the order of the columns names declared in the system.  That would be slightly more efficient than looking up the column values in a map :-).

**Comment by genmeblog** [comment]
For sure! Great idea, this way function can be feed directly with the row data.

**Comment by cnuernber** [comment]
If sort-by-columns could optionally take a map instead of a sequence you could have values in the map that related to ascending or descending order.  Potentially for numeric columns you could have the binary comparison functions (`>` `<`).   So your last example would become:
```clojure
(->> (ds/->dataset [{:a 1 :b 2} {:a 11 :b -2} {:a 1 :b -1}])
     (sort-by-columns-with-orders {:a > :b >}))
```
The execution then becomes a chain of comparators and potentially some form of `(drop-while #(== 0 ...))`.

**Comment by cnuernber** [comment]
Addressed by https://github.com/scicloj/tablecloth
