### ISSUE TITLE
Travis auto-tests are broken

### ISSUE THREAD

**Issue by cnuernber** [techascent/tech.ml.dataset#373]
I honestly don't have the patience to deal with this right now.  Open to fixing travis or switching to github actions - either works for me.

**Comment by iperdomo** [comment]
Hi @cnuernber I would like to offer help with this issue.

I'm familiar with GH actions, not so much with `deps.edn` - old `lein` user here -. Reading the TravisCI definition, the build process seems straight forward. Download some sample dataset and execute some tests via `clj`.

As first step we should port the TravisCI definition to GH actions. Then we can discuss if we can improve it, e.g. different JDKs and versions.

**Comment by cnuernber** [comment]
That sounds perfect to me.  The one snag here is probably going to be mkl and we will need to test when it is possible and avoid when it is not.  The mac-m1 alias does exactly this.  

If you are up for it we would certainly appreciate it.

**Comment by iperdomo** [comment]
I've done some testing locally in an Ubuntu 22.04 VM with openjdk-8, openjdk-11, and openjdk-17 and tests are passing. I'll start working in a fork and open a draft PR when I think is ready for initial review.

**Comment by iperdomo** [comment]
I'll give it a second look at the workflow and see how we can have a build matrix, different JDK versions and potentially architecture

**Comment by cnuernber** [comment]
Thoroughly fixed :-).
