### ISSUE TITLE
provide infinite `idx-seq` to `set-missing` makes cider unresponsive

### ISSUE THREAD

**Issue by keesterbrugge** [techascent/tech.ml.dataset#38]
The following code makes cider unresponsive. Interrupting the repl doesn't work, gives "sync nrepl request timed out (op close)" 

```clj
(-> (ds/->dataset [{:a 1 :b 2}])
    (ds/update-column :b #(tech.ml.dataset.column/set-missing % (range))))
```

When I shut down the jvm process I received an out of memory error in the repl

**Comment by genmeblog** [comment]
It's here: https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/ml/dataset/impl/column.clj#L277

**Comment by genmeblog** [comment]
Looks like row selector can't be infinite sequence. Maybe add `:all` to mark you want to select all rows.

**Comment by genmeblog** [comment]
I also faced the same problem. If infinite sequence is given it should be wrapped into something like `(take (ds/row-count DS) (cycle sequence))` or `(take (ds/row-count DS) (repeat value))`. What do you think?

**Comment by keesterbrugge** [comment]
I've seen libraries choose null padding or cycling the input sequence as standard behaviour but it is usually surprising and often not what you want. Given that it is easy to generate infinite sequences ourselves with functions like `cycle` and `repeat` I think it is better to have only 2 options:
- Either a sequence of length row-count can successfully be taken from the input sequence 
- or error
This avoids surprises.

**Comment by cnuernber** [comment]
That works for set-missing.  For select, you can duplicate rows (like in a join) and this is in fact valid so select cannot have such a limit.

**Comment by cnuernber** [comment]
Hmm, it also works for remove-rows.
