### ISSUE TITLE
left-join fails when options argument is nil

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#384]
When options are passed as `nil` instead of empty map `{}` `left-join` fails.

The main reason is this line: https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/v3/dataset/join.clj#L346 which imho should be `(assoc options :lhs-missing? true)`

**Comment by cnuernber** [comment]
right join had the same issue - what an odd mistake to make...

**Comment by genmeblog** [comment]
Yes, yes, indeed :)
