### ISSUE TITLE
tribuo changes types between input dataset and prediction

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#391]
see https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/tribuo.20prediction.20datatype.20does.20not.20match

```clojure
(ns scicloj.ml.tribuo
  (:require
   [tech.v3.dataset :as ds]
   [tech.v3.dataset.modelling :as ds-model]
   [tech.v3.libs.tribuo :as tribuo])
  (:import
   (com.oracle.labs.mlrg.olcut.config DescribeConfigurable)
   (org.tribuo.classification.sgd.linear LogisticRegressionTrainer)))



(def logreg-trainer (LogisticRegressionTrainer.))

(def dummy-ds
  (->
   (ds/->dataset {:x [1 1] :y [0 1]})
   (ds-model/set-inference-target :y)))
(-> dummy-ds :y seq)
;; => (0 1)


(def m (tribuo/train-classification logreg-trainer dummy-ds))

(->
 (tribuo/predict-classification m dummy-ds)
 :prediction
 seq)
;; => ("0" "0")
 ```

**Comment by behrica** [comment]
I think we should in some form agree on some "standard" behaviour of the various "predict" implementations:

https://github.com/scicloj/scicloj.ml.smile/blob/d17053ef2b15daf36571754131e5c885a2f62706/src/scicloj/ml/smile/classification.clj#L424
https://github.com/scicloj/scicloj.ml.tribuo/blob/e14d1caafa751a84f0ddbc6112ead1ee85947296/src/scicloj/ml/tribuo.clj#L19

`metamorhp.ml` allows to mix various models from different libraries in a single call to 
https://github.com/scicloj/metamorph.ml/blob/d111993af27234db0f7d654e12d0eb384c5d2c5b/src/scicloj/metamorph/ml.clj#L264

This call calculates as well the `loss`, in this line:
https://github.com/scicloj/metamorph.ml/blob/d111993af27234db0f7d654e12d0eb384c5d2c5b/src/scicloj/metamorph/ml.clj#L50

This is very difficult to get right, if the code cannot know, what datatypes to expect in comparing columns:
trueth-col predictions-col
https://github.com/scicloj/metamorph.ml/blob/d111993af27234db0f7d654e12d0eb384c5d2c5b/src/scicloj/metamorph/ml.clj#L50
Exactly here we see as well the complication of "categorical mappings", which could exist (or not) in both sides of the comparison.

**Comment by behrica** [comment]
This is problematic as usual accuracy is calculated by comparing:
[0 1] and ["0" "0"], which is eventually problematic in automatic evaluations.
In `metamorph.ml`   and its `predict` method  I will try to fail on all this situations

**Comment by behrica** [comment]
Any news on this issue ?
The fact that the tribuo trainer changes he "dataype" in its prediction from float to string makes it a bad player among the different models.
A model which is trained on [0 1 0 1 ..]  (as int), should never predict "0" or "1".
I think a well behaving (classification) model should never predict anything which it never saw in training data.
 0 and "0" is not the same in this context.

**Comment by cnuernber** [comment]
I agree

**Comment by behrica** [comment]
I think the "problem" here is , that the Classification in Tribuo has only foreseen, that training data target column is of type "Label" (which is a String fundamentally).
In java this is guarantied by the type system and its generic types.
In Clojure we circumvent this, which in some for shows a "bug" in Tribuo, but it cannot happen using Java Code.
(so it's not a bug)

**Comment by behrica** [comment]
I went deeper.
The issue is this line:
https://github.com/techascent/tech.ml.dataset/blob/b0896cc6116ad6aa049fb7f1b955e9fe49b07ae8/src/tech/v3/libs/tribuo.clj#L126

in which the code converts keyword,numbers and Strings to "string",
and forgets about initial type.
Probably we need to remember" the original type in some way, and convert back after prediction.

**Comment by behrica** [comment]
I a thinking know, that this is not solvable on the level of tech.ml.dataset,
as it would require that "train" and "predict" to communicate the "label type", which is not possible in the current way

**Comment by behrica** [comment]
I solved it in scicloj.ml.tribuo
