### ISSUE TITLE
.xlsx loading fails if a column has a number for a name

### ISSUE THREAD

**Issue by kiramclean** [techascent/tech.ml.dataset#408]
Loading an .xlsx spreadsheet fails if a column has a number for a name. For example this spreadsheed throws `Don't know how to create ISeq from: java.lang.Double`:  [example_XLSX.xlsx](https://clojurians.zulipchat.com/user_uploads/9096/-jsU5FU1EGuYIVNhcb__nLmB/example_XLSX.xlsx)

**Comment by harold** [comment]
Reproduced by downloading the file and...

```clojure
user> (require '[tech.v3.dataset :as ds])
nil
user> (require '[tech.v3.libs.fastexcel])
Reflection warning, tech/v3/libs/fastexcel.clj:111:22 - reference to field getStableId on org.dhatim.fastexcel.reader.Sheet can't be resolved.
nil
user> (ds/->dataset "/home/harold/Downloads/example_XLSX.xlsx")
Execution error (IllegalArgumentException) at tech.v3.dataset.io.context$options$reify__31940/apply (context.clj:93).
Don't know how to create ISeq from: java.lang.Double
```

Suspicious: https://github.com/techascent/tech.ml.dataset/blob/b0896cc6116ad6aa049fb7f1b955e9fe49b07ae8/src/tech/v3/dataset/io/context.clj#L93

Similar:

```clojure
user> (empty? "foo")
false
user> (empty? 0)
Execution error (IllegalArgumentException) at user/eval59523 (form-init3289276633768178084.clj:26).
Don't know how to create ISeq from: java.lang.Long
user> (empty? 0.0)
Execution error (IllegalArgumentException) at user/eval59525 (form-init3289276633768178084.clj:29).
Don't know how to create ISeq from: java.lang.Double
```

---

Maybe if it's a number, call `str` on it? Hard to know what the cleanest fix might be. hth

**Comment by kiramclean** [comment]
I assume you noticed already, but this is also the case for `.xls` files, e.g. 
[example_XLS.xls](https://github.com/techascent/tech.ml.dataset/files/15298324/example_XLS.xls)
