### ISSUE TITLE
ClassCastException when using into on Instant column

### ISSUE THREAD

**Issue by mk** [techascent/tech.ml.dataset#413]
We're running into a ClassCastException when using a tech.v3.dataset with Clerk, originally reported as nextjournal/clerk#677. Here's a small repro using `techascent/tech.ml.dataset {:mvn/version "7.030"}`:

```clojure
(require '[tech.v3.dataset :as ds])

(def ds
  (ds/->dataset {:x (range 5)
                 :y (repeatedly 5 #(java.time.Instant/now))}))

(into [] (take 3) (:x ds)) ;; works
(into [] (take 3) (:y ds)) ;; throws ClassCastException: class clojure.lang.Reduced cannot be cast to class clojure.lang.ITransientCollection (clojure.lang.Reduced and clojure.lang.ITransientCollection are in unnamed module of loader 'app')
```

Is this expected behavior or a bug that could be fixed?

**Comment by cnuernber** [comment]
Yes I believe it is a bug; we will look into it - thanks for the report.
