### ISSUE TITLE
unexpected "distinct" of float columns after categorical->number

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#414]
```
(->
  (tc/dataset {:x1 [1 2 4 5 6 5 6 7]
               :x2 [5 6 6 7 8 2 4 6]
               :y [:a :b :b :a :c :a :b :d]})
  (ds/categorical->number [:y])
  (get :y)
  distinct)
```
->  -> (2.0 3 2 1 0)

So we have 2.0 and 2 in the column :y, which seems to be wrong.

see here: https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/unexpected.20.22distinct.22.20of.20float.20columns

**Comment by cnuernber** [comment]
I think categorical->number should just return a long column and not a floating point column.  The long cclumn will auto-convert to reasonable double values if asked specifically for a double representation.

**Comment by harold** [comment]
:+1:
