### ISSUE TITLE
scripts/run-tests not always correctly detecting java version used by Clojure

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#417]
resulting in incorrect aliases and compile / run errors regarding module configuration

see here:
https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/tech.2Edataset.20not.20compiling.20on.20jdk.2017

**Comment by behrica** [comment]
Maybe I should add that I am using NixOS.
This is probbaly special in this sense.
So the JVM used by Clojure and the "normal" JVM are unrelated.

**Comment by behrica** [comment]
I am not sure if you are interested in adding a devcontainer config to this project.
"inside" the devcontainer all test run sucessfull.
We can add as well a new GitHub action which runs all tests inside the devcontainer.
I see this "additional" to the existing action

The existing action runs on different JDKs, while a devcontainer bring "one known to work environment",
which "freezes everything". It allows "easier onboarding of potential collaborators".

(as for example all test just pass inside the container)

I can make a PR with the config, if you want.

**Comment by cnuernber** [comment]
I would like to start by getting rid of the profile altogether perhaps and then back off as is necessary to support current platforms. 

It seems to me that github workflow test.yml already serves to be the 'one true environment' in that respect.

**Comment by behrica** [comment]
Yes, but the test.yml environment cannot be re-created locally on keypress.
Having .devcontainer config allows as well to use Github Codespaces, which is 
has a large free tier

**Comment by behrica** [comment]
To get all tests pass for tech.ml.dataset is not "trivial", as you know.
mkl installation for example.
I agree that it can be "viewed" in the test.yml but not "recreated" on keypress.

**Comment by behrica** [comment]
As I have it, I make a PR, and then you decide.

**Comment by cnuernber** [comment]
I think we hit a middle ground.  I accepted the PR as a valid devcontainer setup clearly may help you and others work who are experimenting with environments *and* I made sure that jdk-21 is supported in the test matrix.
