### ISSUE TITLE
JVM crash starting with TMD 7.0.33

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#437]
see here

https://clojurians.zulipchat.com/#narrow/channel/236259-tech.2Eml.2Edataset.2Edev/topic/JVM.20crash.20starting.20with.20TMD.207.2E0.2E33

**Comment by cnuernber** [comment]
This is very very helpful.  The unit tests of libpython-clj fail with latest dtype-next -- probably due to changes related to pass-by-value support and such.  Will fix there and reference this issue.

**Comment by cnuernber** [comment]
Its because the definition of dt-ffi/convertible-to-pointer now return true for Long's which does make sense but libpython-clj relies on that not being the case - had nothing to do with generated bindings just library mechanics.

**Comment by cnuernber** [comment]
This is fixed in a backwards compatible way in libpython-clj version 2.026.
