### ISSUE TITLE
rows selection enhanced

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#44]
I can imagine such helper functions:

1. head - select first `n` rows (equivalent to `(select-rows (range n))`
2. tail - select last `n` rows
3. sample - return `n` random rows (with repetitions or not)
4. shuffle (permute) dataset
5. unique (whole dataset) by rows

**Comment by cnuernber** [comment]
Unique is hardcore - you mean something like keep every row in a set and don't allow repeat rows or do you mean unique-by-column(s)?
head,tail,sample,shuffle, (rand-nth), all of those make sense.

**Comment by cnuernber** [comment]
Leaving  unique/distinct for later as I think that one requires a bit more discussion.

**Comment by genmeblog** [comment]
Unique - removing row duplicates in whole dataset. But it's not urgent :)

**Comment by harold** [comment]
There is also Pandas' `drop_duplicates`, which I've needed in the past: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html
