### ISSUE TITLE
`count` on `ds/missing`

### ISSUE THREAD

**Issue by harold** [techascent/tech.ml.dataset#440]
Not urgent or critical (obviously), but if this is easy to extend and makes sense?

```clj
user> (require '[tech.v3.dataset :as ds])
nil
user> (ds/missing (ds/->dataset {:x [0 1 nil 3 4 nil nil 7]}))
{2,5,6}
user> (count *1)
Execution error (UnsupportedOperationException) at user/eval65711 (REPL:11181).
count not supported on this type: RoaringBitmap
user> (.getCardinality *1)
3
```

**Comment by cnuernber** [comment]
Its not possible to extend count to roaring bitmaps - dtype/ecount works here as it is protocol based (and thus much slower) - but perhaps (ds/missing) should return some wrapper on top of the roaring bitmap and not return the raw bitmap - that is honestly a bit of an API wart as there may be cases where we don't want to return the roaring bitmap itself.

**Comment by harold** [comment]
oic - hadn't looked at how it would actually work.

There's probably a good bit of code in the world that's tied to `ds/missing` returning a concrete roaring bitmap - it's not worth breaking anything imo.
