### ISSUE TITLE
cols selection enhance

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#45]
We have some variant for column(s) selection

1. `column` and `columns` returns columnar data type
2. `select-columns` returns dataset

That's ok. I would add:

1. `select-column` - to create dataset with one column
2. Enhance arguments to `select-columns`:
    - seq of names - as currently
    - map - rename and select
    - optionally: sequence which can contain name or map to mix two above

**Comment by cnuernber** [comment]
Adding map.  Leaving out optional for now :-).
