### ISSUE TITLE
dataset namespace loading time

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#46]
Require dataset is very, very slow, it takes 25s in my machine

```clojure
user> (time (require '[tech.ml.dataset :as ds]))
"Elapsed time: 25646.0355 msecs"
nil
```

**Comment by cnuernber** [comment]
Yep, this one is a really hard one.  Providing a uniform interface on top of things like the java.time system takes a while.

Potentially we could do several and the easiest is to aot namespaces.  Aside from that we are in a space where the performance requirements to play in this space have a significant compile time implication and I am pushing Clojure's compile time performance.

**Comment by genmeblog** [comment]
Yes, it's tough for sure. For me it's ok but we've received the request to speedup initialization of `clojisr` (which relies on tech.ml.dataset). So this topic will be appearing from time to time.

**Comment by cnuernber** [comment]
What we have done in leaf nodes is (in leiningen) `:aot [tech.ml.dataset]`.  This does completely solve that require problem at the cost of making upgrades without a lein clean flaky.

**Comment by cnuernber** [comment]
The new dataset (5.X branch) takes about 1/2 the time the old one did.  I think this is the best we can do given the state of the current Clojure compiler.
