### ISSUE TITLE
csv with empty column's name

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#52]
When I export dataset from R which has row names, resulting CSV looks like that:

```csv
"","Rural Male","Rural Female","Urban Male","Urban Female"
"50-54",11.7,8.7,15.4,8.4
"55-59",18.1,11.7,24.3,13.6
"60-64",26.9,20.3,37,19.3
"65-69",41,30.9,54.6,35.1
"70-74",66,54.3,71.1,50
```

CSV contains empty string as the first column's name (row names). In such case import fails. I think it would be great to assign some dummy name in such case.

**Comment by cnuernber** [comment]
What about an integer index?  Like 0.  This is what would be assigned if there were no header names.

**Comment by genmeblog** [comment]
Perfectly ok. Maybe generally column number in case when other columns have missing columns.
