### ISSUE TITLE
Unique, drop duplicates

### ISSUE THREAD

**Issue by cnuernber** [techascent/tech.ml.dataset#54]
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html

https://www.rdocumentation.org/packages/data.table/versions/1.12.8/topics/duplicated

Pandas seems strictly better to be as you get a choice between if you want the first or last occurrence.

Continuation of #44 .

Using a [parallel-map-reduce](https://github.com/techascent/tech.parallel/blob/master/src/tech/parallel/for.clj#L10)  algorithm of just iterating every row and building a hashtable of hash codes to index array lists seems like a good way of doing this.  Then potentially there is a fast combine method of the hashtables that results in the set of indexes to either add or remove.  That is sort of like `(group-by-index identity dataset)` followed by iterating the indexes and taking first or last or butfirst or butlast.

I guess that also implies an algorithm to get the hash value of a given row which in and of itself is a thing.

**Comment by harold** [comment]
Yup, the `"last"` option here has been clutch in the past - thinking of time-series datasets where the most recent instance is the most interesting (price arbitrage, etc.)

**Comment by genmeblog** [comment]
Just discovered that this works:

`(ds/unique-by identity DS :column-name-seq (ds/column-names DS))`

But this do not preserve the order.

**Comment by cnuernber** [comment]
The code to that one is pretty minimal:
```clojure
(defn unique-by
  "Map-fn function gets passed map for each row, rows are grouped by the
  return value.  Keep-fn is used to decide the index to keep.

  :keep-fn - Function from key,idx-seq->idx-seq.  Defaults to first."
  [map-fn dataset & {:keys [column-name-seq keep-fn]
                    :or {keep-fn default-unique-by-keep-fn}}]
  (->> (group-by->indexes map-fn dataset column-name-seq)
       (map (fn [[k v]] (keep-fn k v)))
       (select dataset :all)))
```
Fixing order would be efficiently done with a call to sort or construction of a bitmap.  Is there a use case for knowing the indexes that were dropped?

I wonder how efficient that really is, like for instance is the hash code cached once calculated.  I need to check clojure.lang.APersistentMap (the base class of [FastStruct](https://github.com/techascent/tech.ml.dataset/blob/master/java/tech/ml/dataset/FastStruct.java)).

**Comment by cnuernber** [comment]
Hell yeah Rich,Alex, APersistentMap is well done.  Man, that is actually a pretty big time/correctness bonus.

**Comment by cnuernber** [comment]
That makes me wonder if readers couldn't provide default implementations that derived from APersistentVector and would provide a similarly cacheable and correct default pathway.

**Comment by genmeblog** [comment]
> Is there a use case for knowing the indexes that were dropped?

I don't know. But I feel that consistent strategy should be used. Like keep last or keep first.

**Comment by harold** [comment]
> Like keep last or keep first.

I think of Clojure semantics being typically 'keep first' (at least, this is how we've typically implemented `unique-by`.

But, it's neat that in pandas you can specify with the `keep` parameter: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html
