### ISSUE TITLE
remove-rows

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#55]
I don't see function to discard some rows by index.

**Comment by genmeblog** [comment]
`drop-rows`, just found it.

**Comment by cnuernber** [comment]
Hmm, I didn't remember!  Implementation of drop rows looks fine though, but adding remove-rows as an alias doesn't hurt anything.  There is also 'remove-columns' and 'drop-columns', I just don't know which will be a better mnemonic.

**Comment by genmeblog** [comment]
I don't know either. R uses negative indexes for that (which is imho bad pattern). Pandas uses drop. I was looking for remove, I don't know why though :) And yes, we can have both.
