### ISSUE TITLE
options when dataset is created

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#59]
We have two ways of api creation:

1. From map or pairs [name seq] using `name-values-seq->dataset`
2. Other cases via `->dataset` or `->>dataset`

options are passed differently: first on variadic position, latter as second argument.

BTW there should be one function (you can infer if something is map or sequence of sequences (length=2)

**Comment by cnuernber** [comment]
I would love to have one function.  Probably can be inferred although a the name-values-seq->dataset can take a sequence of tuples not just a map.  So you can have a sequence of maps, a sequence of tuples, or a thing (string, input stream).  That should be inferrable, you are very right.

**Comment by genmeblog** [comment]
I'm playing with an simpler api which is natural step (for me) after working with data.table and dplyr. I hope to share it today. I've made one function which works as I described above. Stay tuned.

**Comment by cnuernber** [comment]
This is now fixed in the the library (you can pass maps of name->data now)

And fixed via:
https://github.com/scicloj/tablecloth
