### ISSUE TITLE
zipped dataset

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#60]
I found a page full of datasets but the one I've chosen is zipped. Can you add zip format as well? (it's supported by Java SDK fortunately).

**Comment by genmeblog** [comment]
I tried input stream, but it doesn't work

```clojure
(ds/->dataset (java.util.zip.ZipInputStream. (clojure.java.io/input-stream "cup98lrn.zip")))
```

**Comment by harold** [comment]
The API is a little more complicated than that, zip files can have arbitrary file systems inside them.

If the zip contains exactly one file, you can do something like this, perhaps:
```(clojure)
  (let [zipfile (ZipFile. (io/file "test/data/colornames.zip"))
        entry (->> zipfile
                   (.entries)
                   (iterator-seq)
                   (first))]
    (ds/->dataset (.getInputStream zipfile entry)))
```

**Comment by genmeblog** [comment]
Ah, indeed... So nothing to do here.

**Comment by cnuernber** [comment]
Not at this level maybe.  tech.io could, however, have better support for zip.

**Comment by genmeblog** [comment]
@behrica proposed to make possible reading zip archive with the only file inside. What do you think about that?

**Comment by cnuernber** [comment]
Seems reasonable

**Comment by behrica** [comment]
Came to it again and could not see, why

it works to do 
(ds/dataset "./players.csv.gz")

while this fails.
(ds/dataset "./players.csv.zip")


So I would indeed propose for any ".zip" to 

1. open the zip stream
2. if > 1 file -> fail
3. see if file  suffix of the one file is supported (or specified with :file-type)
  - no:  -> fail
  - yes: open as usual

**Comment by behrica** [comment]
Th single file "zip" archies do get more and more common.
I think because "gzip" is not preinstalled on Windows or at least not commonly used

**Comment by harold** [comment]
Agreed- this would be a nice convenience to have at this specific spot where there is a 1-1 correspondence between a single file and a dataset.

I also like the idea of looking at the suffix of the compressed file inside the zip file system. I believe a common case here would be files named (e.g.) `clickstream-2021-09-14.zip` with a single file inside named (e.g.) `clickstream.csv`. So, the fact that there's a `.csv` inside won't always be indicated in the filename of the `.zip` file itself.

---

fwiw, I can also confirm that `.zip` is more common on Windows than `.gz`

**Comment by cnuernber** [comment]
https://techascent.github.io/tech.ml.dataset/tech.v3.dataset.zip.html

**Comment by cnuernber** [comment]
There is now built-in support for reading/writing single dataset zip files assuming the suffix indicates the file type.
