### ISSUE TITLE
new function: beside unroll-column, add indexed-unroll-column?

### ISSUE THREAD

**Issue by keesterbrugge** [techascent/tech.ml.dataset#63]
Hi, 
I'm saw the new function `unroll-column` that you added. I use similar functionality often, but in my use cases I almost always also need the index of the element in the sequence that I unroll, e.g. 
```clj
(-> (ds/->dataset [{:a 1 :b [2 3]}
                              {:a 2 :b [4 5 6]}
                              {:a 3 :b :a}])
               (ds/indexed-unroll-column :b))
;; =>
_unnamed [6 3]:
| :a | :b | :index
|----+----+----|
|  1 |  2 |  0 |
|  1 |  3 |  1 |
|  2 |  4 |  0 |
|  2 |  5 |  1 |
|  2 |  6 |  2 |
|  3 | :a |  0 |
```
The scalar doesn't have an index, but perhaps defaulting to index value zero is appropriate. 
Do you think adding a function like this `indexed-unroll-column` would be of additional value to the library?

**Comment by genmeblog** [comment]
maybe instead of separated function this could be an option `index?` or something like that.

ts

**Comment by cnuernber** [comment]
Index could be an option for a lot of operations (join for example).

You can always (on the cheap!) add an index:
```clojure
(-> (ds/add-or-update-column ds :index (range (ds/row-count ds)))
    (ds/unroll-column :b))
```

**Comment by keesterbrugge** [comment]
Hi @cnuernber,
your example would add a row index, whereas what I was aiming for was the index of the element in the vector that is being unrolled. You can see it in the example

**Comment by cnuernber** [comment]
Ah I do see that now.  Yes, that is a an interesting piece of info that you can't get efficiently any other way.  Got it.
