### ISSUE TITLE
joins on multiple columns

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#66]
As I see in the code it's currently not possible.
But I think this could be valuable enhancement.

I'm thinking currently about workaround where I make artificial column with values of other columns as string and making join on this. But this can't be optimal way I suppose.

**Comment by cnuernber** [comment]
This is probably optimal :-).  You will create the column and it will be read exactly once in the join code in multiple threads thus giving the threads space to do the work in parallel - 

https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/ml/dataset/join.clj#L50

**Comment by cnuernber** [comment]
Closing this as I believe you are satisfied :-).

**Comment by cnuernber** [comment]
Fixed in new release.  :left-column-names and :right-column-names are now maps of originalname->newname that would make that pathway insulated from a mistake in the renaming algorithm.
