### ISSUE TITLE
`dfn/max` dosn't work on column

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#67]
```clojure
(dfn/log (DS :V1))
;; => [0.0 0.6931471805599453 0.0 0.6931471805599453 0.0 0.6931471805599453 0.0 0.6931471805599453 0.0]

(dfn/mean (DS :V1))
;; => 1.4444444444444444

(dfn/max (DS :V1))
;; excpetion: Failed to find op: :max

(apply dfn/max (DS :V1))
;; => 2
```

**Comment by cnuernber** [comment]
We do have  `reduce-max`.

**Comment by cnuernber** [comment]
I had to differentiate between functions that return scalars and functions that return readers when a reader is passed in else it is hard to differentiate between a mistake.  This is similar to `+`.  Maybe this decision could be revisited as it has caused some confusion.

**Comment by genmeblog** [comment]
Yes, sometimes it's confusing. In above example: why `max` differs from `mean`, both are applied on vectorized input (column, seq, reader) and both return single value.

**Comment by genmeblog** [comment]
BTW, `dfn/pow` doesn't work on int datatype, `dfn/rem` and `dfn/quot` doesn't work on floats.

**Comment by cnuernber** [comment]
They don't though:
```clojure

user> (require '[tech.v2.datatype :as dtype])
nil
user> (require '[tech.v2.datatype.functional :as dfn])
nil
user> (dfn/max [1 2 3] [3 4 5])
[3 4 5]
user> (dfn/reduce-max [1 2 3])
3
```

You hit on it exactly.  Vectorized `max` returns a vector while `reduce-max` always returns a scalar.  If you extend the clojure core max function to vector space it would return a vector, not a scalar.   Clojure's max function cannot be called with one argument.

**Comment by cnuernber** [comment]
`rem` and `quot` I think don't work on floats in normal clojure land but `pow` should work on integers and just return a floating point value.

**Comment by genmeblog** [comment]
Ah see :) Good point. I think clear guide describing every function in one table could be helpful.

Regading pow, quot and mod, check this out:

``clojure
(DS :V1)
;; => #tech.ml.dataset.column<int64>[9]
;; :V1
;; [1, 2, 1, 2, 1, 2, 1, 2, 1, ]

(dfn/pow [1 2 3] 2)
;; => [1.0 4.0 9.0]

(dfn/pow (DS :V1) 2)
;; exception: Unsupported datatype for operation: :int64

(rem 12.3 4.4)
;; => 3.5

(quot 11.2 4.3)
;; => 2.0

(dfn/rem (DS :V1) 1.0)
;; exception: Operator only supports integer datatypes, :float64

(dfn/quot (DS :V1) 1.0)
;; exception: Operator only supports integer datatypes, :float64

(DS :V3)
;; => #tech.ml.dataset.column<float64>[9]
;;    :V3
;;    [0.5000, 1.000, 1.500, 0.5000, 1.000, 1.500, 0.5000, 1.000, 1.500, ]

(dfn/rem (DS :V3) 2)
;; exception: Operator only supports integer datatypes, :float64

(dfn/quot (DS :V3) 1)
;; exception: Operator only supports integer datatypes, :float64
```

**Comment by cnuernber** [comment]
Oh, I stand corrected.  I didn't realize that would work like that.

**Comment by cnuernber** [comment]
All the math issues like that should be fixed.  bit-and and friends still require integers but rem/pow, etc all will work without complaint :-).

All binary operators have a `reduce-*` variant, so there is reduce-pow, reduce-quot, etc.  Whether these are useful I don't know but but it is easiest just to auto-generate them and I believe a more traditional numeric language would just generate the function on demand.  Now I guess I need to go back and check that the reduce variants also accept all the datatypes.
