### ISSUE TITLE
how to replace missing value?

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#69]
Is there an easy way to replace `missing` value to provided?
I know that there is pipeline operation but how to do on column?

**Comment by cnuernber** [comment]
1. Meaning without changing the missing set change the provided missing value?

2.  Or do you mean set all the missing indexes to another value and clear the missing set?

The way the pipeline does 2 it is to use `tech.v2.datatype.readers.update-reader/update-reader` and `tech.v2.datatype.bitmap/bitmap->bitmap-map`.    I don't have a way currently to change the presented missing value but it could logically be part of the column metadata.

**Comment by genmeblog** [comment]
Number 2. I need to set it to the value and clear the missing set. Ok, I take a look at pipeline version. Thanks.

**Comment by genmeblog** [comment]
Looks I need to continue.

I see that BitmapMap accepts bitmap (result of `col/missing` for example) and single value which is used as a replacement later.
I can provide regular hashmap to `update-reader`, and everything is fine. But when map is incomplete I'm losing missing values.
Also `new-column` doesn't parse against missing values.

```clojure
(def col (col/new-column :a [1 2 nil 3 4 nil nil nil 11]))
col
;; => #tech.ml.dataset.column<object>[9]
;;    :a
;;    [1, 2, , 3, 4, , , , 11, ]

;; ???
(col/missing col)
;; => #{}

(def ds (ds/name-values-seq->dataset {:a [1 2 nil 3 4 nil nil nil 11]}))

(col/missing (ds :a))
;; => #{2,5,6,7}

(def ds1 (ds/assoc ds :a (update-rdr/update-reader (ds :a) {2 2222 5 5555 6 6666 7 7777})))

(ds1 :a)
;; => #tech.ml.dataset.column<int64>[9]
;;    :a
;;    [1, 2, 2222, 3, 4, 5555, 6666, 7777, 11, ]

(col/missing (ds1 :a))
;; => #{}

(def ds2 (ds/assoc ds :a (update-rdr/update-reader (ds :a) {2 2222})))

(ds2 :a)
;; => #tech.ml.dataset.column<int64>[9]
;;    :a
;;    [1, 2, 2222, 3, 4, -9223372036854775808, -9223372036854775808, -9223372036854775808, 11, ]

;; ???
(col/missing (ds2 :a))
;; => #{}
```

**Comment by cnuernber** [comment]
Try create a completely new column (`tech.ml.dataset.column/new-column`) and providing the missing set you think should be there.  The current default, upon being provided a reader, is to have no missing set as the readers themselves don't have a missing set - that is a column-specific datastructure.

**Comment by genmeblog** [comment]
ok, got it.

**Comment by genmeblog** [comment]
Sorry to reopen it again:

```clojure
(def ds (ds/name-values-seq->dataset {:a [1 2 nil 3 4 nil nil nil 11]}))

(col/missing (ds :a))
;; => #{2,5,6,7}

(ds :a)
;; => #tech.ml.dataset.column<int64>[9]
;;    :a
;;    [1, 2, -9223372036854775808, 3, 4, -9223372036854775808, -9223372036854775808, -9223372036854775808, 11, ]
```

Why I see `Long/MIN_VALUE` where I should see nothing? I think when column is printed it should follow the same path as displayed dataset.

**Comment by cnuernber** [comment]
I agree.  Good point.
