### ISSUE TITLE
left/right join - column name

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#70]
Can you expose function which will generate left/right join duplicated column names? I need to know which columns are added and what are their names.
Currently I had to copy `colname->str` and `similar-colname-type` and made assumption about adding "right." prefix (after left join on _unnamed datasets).

Something like `(colname-after-join colname lhs rhs join-type)`

**Comment by cnuernber** [comment]
I was hoping people wouldn't need that but I knew it would happen :-).  That algorithm is not fun but yes, as part of the dataset metadata I can have a map of lhs-names->result-names and a map of rhs-names->result-names.

**Comment by genmeblog** [comment]
haha :) In `pivot->wider` I do left-join in reduce and I need to remove one column (the column which is used to join). I figured out how to construct its name, but in general this information could be helpful I suppose.

**Comment by cnuernber** [comment]
Well, what it does is give me license to change the column name algorithm which I will undoubtedly need to do at some point in the future.
