### ISSUE TITLE
Read dataset with more than 512 columns

### ISSUE THREAD

**Issue by lccambiaghi** [techascent/tech.ml.dataset#72]
As title. Is there a way to bypass the limit of the univocity parser of 512 maximum columns?

Thank you.

**Comment by cnuernber** [comment]
What a ridiculous hardset number.  Here is an issue about it on univocity:
https://github.com/uniVocity/univocity-parsers/issues/301

I will set the default higher and provide an option to set it to whatever you like.

**Comment by lccambiaghi** [comment]
Thank you! In my use case I need 2000 columns!

**Comment by harold** [comment]
640,000 columns ought to be enough for anyone. :stuck_out_tongue_winking_eye:

**Comment by cnuernber** [comment]
New release is up :-).

**Comment by lccambiaghi** [comment]
Thank you so much for your quick fix!!
