### ISSUE TITLE
Support for reading .parquet files

### ISSUE THREAD

**Issue by lccambiaghi** [techascent/tech.ml.dataset#75]
Hi, another "would be nice if.." feature request from me! Everybody likes .csv files but the Apache Arrow project is more and more popular in industry. Spark also uses partitioned parquet files if I recall correctly. It is an efficient columnar file format which carries schema information about its columns! If it can be useful, smile already has bindings implemented here: https://github.com/haifengl/smile/blob/master/clojure/src/smile/io.clj .

**Comment by cnuernber** [comment]
1.  I didn't know that smile had a dataframe implementation :-).
2.  Do you have any parquet (or arrow) files yourself?  

Agreed that people are using those file formats.  I just would like an actual use case from someone if possible.  Currently focused on JDBC integration as the next sort of data source/sink.

**Comment by lccambiaghi** [comment]
I found these small samples in github: https://github.com/Teradata/kylo/tree/master/samples/sample-data/parquet . For my use case I would be happy enough to read a file into a tech.ml.dataset. I understand you have other priorities, I was just wondering whether it would be an easy integration given the smile IO bindings. However I don't really know how much work it is needed to go from there to a dataset...

**Comment by cnuernber** [comment]
I bet it isn't a lot of work especially with the smile bindings to look through and with the csv and xlxs systems working.  It's a good thing to track.

**Comment by cnuernber** [comment]
Actually, flipping this around a bit I bet it isn't a lot of work to convert from a smile dataframe to a tech.ml.dataset (and back).  That seems to be the move here.

**Comment by cnuernber** [comment]
This is transitively support at this point.  We can convert a smile DataFrame to a dataset via `->dataset` and a dataset to a DataFrame via `dataset->smile-dataframe`.  

So you can parquet all you want.   A further issue may be 'missing values do not come in from loading parquet/arrow files` or `please support zerocopy arrow loading` both of which are considerably harder *but* for now we can say we support apache arrow and parqet via smile.

**Comment by lccambiaghi** [comment]
Hi Chris, that sounds really nice, thank you for the hard work! 

I cannot however read parquet files with the latest beta, this is the error:
```
Execution error (ClassNotFoundException) at java.net.URLClassLoader/findClass (URLClassLoader.java:382).
org.apache.parquet.io.api.RecordMaterializer
```

**Comment by cnuernber** [comment]
Ah, I should have linked to the dependencies in this issue.  I am really glad this works for you now :-).
