### ISSUE TITLE
converting column to java array

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#81]
`col/to-double-array` converts any numerical column into double array. What if I want to convert to an array of column type? I've found `dtype/as-array` but there are cases when it returns `nil`, like column `:V2`:

```clojure
(def DS (ds/name-values-seq->dataset {:V1 (take 9 (cycle [1 2]))
                                      :V2 (range 1 10)
                                      :V3 (take 9 (cycle [0.5 1.0 1.5]))
                                      :V4 (take 9 (cycle [\A \B \C]))}))

DS
;; => _unnamed [9 4]:
;;    | :V1 | :V2 |    :V3 | :V4 |
;;    |-----|-----|--------|-----|
;;    |   1 |   1 | 0.5000 |   A |
;;    |   2 |   2 |  1.000 |   B |
;;    |   1 |   3 |  1.500 |   C |
;;    |   2 |   4 | 0.5000 |   A |
;;    |   1 |   5 |  1.000 |   B |
;;    |   2 |   6 |  1.500 |   C |
;;    |   1 |   7 | 0.5000 |   A |
;;    |   2 |   8 |  1.000 |   B |
;;    |   1 |   9 |  1.500 |   C |

(map meta (ds/columns DS))
;; => ({:name :V1, :size 9, :datatype :int64}
;;     {:name :V2, :size 9, :datatype :int64}
;;     {:name :V3, :size 9, :datatype :float64}
;;     {:name :V4, :size 9, :datatype :object})

(dtype/as-array (DS :V1))
;; => {:offset 0, :length 9, :java-array #object["[J" 0x6b6792d3 "[J@6b6792d3"]}

;; ???
(dtype/as-array (DS :V2))
;; => nil

(dtype/as-array (DS :V3))
;; => {:offset 0, :length 9, :java-array #object["[D" 0x6dbb724f "[D@6dbb724f"]}

(dtype/as-array (DS :V4))
;; => {:offset 0, :length 9, :java-array #object["[Ljava.lang.Object;" 0x60fbd93c "[Ljava.lang.Object;@60fbd93c"]}
```

**Comment by genmeblog** [comment]
Also when column contains missing values `dtype/as-array` returns `nil`

**Comment by genmeblog** [comment]
I probably misused `dtype/as-array`, maybe there is better functions for that.

**Comment by genmeblog** [comment]
`dtype/make-array-of-type` looks like valid solution, right?

**Comment by cnuernber** [comment]
That will work, `(make-container :java-array column-dtype column)` will work, and dtype/->array-copy will always work. 

as-array only works when the column's datastore can be represented by an array.  This fails in a lot of cases like for instance when you have done a 'select' operation or offset the buffer or any number of things.  If you code can handle arrays with offsets (like System/arraycopy), then ->sub-array will return the backing store as array when possible.

Any row-selection operation, however, makes the in-place array conversions impossible so ->array-copy is my recommendation if you want a one-liner and then make-container is the general purpose utility that can also do light typecasting (equivalent to 'static-cast' in c++).

**Comment by cnuernber** [comment]
```clojure
(def DS (ds/name-values-seq->dataset {:V1 (take 9 (cycle [1 2]))
                                      :V2 (range 1 10)
                                      :V3 (take 9 (cycle [0.5 1.0 1.5]))
                                      :V4 (take 9 (cycle [\A \B \C]))}))

user> (map dtype/->array-copy DS)
([1, 2, 1, 2, 1, 2, 1, 2, 1]
 [1, 2, 3, 4, 5, 6, 7, 8, 9]
 [0.5, 1.0, 1.5, 0.5, 1.0, 1.5, 0.5, 1.0, 1.5]
 [\A, \B, \C, \A, \B, \C, \A, \B, \C])
```

**Comment by cnuernber** [comment]
->array-copy, btw, boils down into System/arraycopy (which is ridiculously fast) when possible.

**Comment by genmeblog** [comment]
Ok, thanks, closing since it's nothing to do here.
