### ISSUE TITLE
column-map executes function everytime when dataset is used

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#83]
Looks like `column-map` is lazy but every time I use dataset mapping function is called again and again.

```clojure
(def DS (ds/name-values-seq->dataset {:a [1 2]
                                      :b [3 4]}))

(def counter (atom 0))

(defn inc-with-counter
  [v]
  (swap! counter inc)
  (inc v))

(def processed (ds/column-map DS :result inc-with-counter :a))

@counter
;; => 0

processed
;; => _unnamed [2 3]:
;;    | :a | :b | :result |
;;    |----|----|---------|
;;    |  1 |  3 |       2 |
;;    |  2 |  4 |       3 |

@counter
;; => 2

processed
;; => _unnamed [2 3]:
;;    | :a | :b | :result |
;;    |----|----|---------|
;;    |  1 |  3 |       2 |
;;    |  2 |  4 |       3 |

@counter
;; => 4
```

**Comment by cnuernber** [comment]
Yes, this is expected.  Readers are lazy but noncaching.  So the result is calculated every time the the index is accessed.  

`dtype/clone` is your friend here as it will create a concrete version of the dataset (or just the column).

**Comment by genmeblog** [comment]
Hmmm... this can cause problems I suppose. Imagine mapping columns on big dataset with slow function.  After several operations such dataset will be not usable since every access will lead to recalcuating everything...

What about `(ds/add-or-update-column DS :V1 (dfn/sqrt (DS :V1)))` ? `sqrt` will be called every time I access `:V1` ?

**Comment by cnuernber** [comment]
Yes, for sure it will.  If you have a big dataset and a slow function then 'clone' that particular column after the operation.  So far the average case is that it has been unnoticeable as compared to other operations.

There really isn't an alternative here.  If it is lazy and random-access, then it cannot be caching else it has to increase the memory usage of the system dramatically.  This is an important difference between this library and, for instance, data.table or Pandas.  

This is why I keep saying that you clone the dataset to realize all of the operations.

**Comment by genmeblog** [comment]
I should have missed that information, which seems to be highly important. Ok then, I need to think where this can be problematic.

**Comment by cnuernber** [comment]
Or rather, I can't think of a viable alternative that doesn't increase the size of the dataset or take away important options.

The flip side of that is that you can schedule the execution of your operations separate from the definition of your operations which is something that is not available with other dataset libraries.  So
if you have a set of columns that are linear manipulations of other columns such as [here](https://github.com/cnuernber/ames-house-prices/blob/master/src/clj_ml_wkg/ames_house_prices.clj#L302) you can build out the manipulations and then call clone once.  This avoids creating temporary columns.

**Comment by cnuernber** [comment]
Moving way forward, this a very rough approximation of the programmatic model behind TVM where you define the algorithm once and then you can schedule it later however you like to take advantage of different hardware or specific aspects of the data.

**Comment by genmeblog** [comment]
I think I can see all benefits and issues. Such delayed evaluation will play well in cases you described. I just need to figure out where the traps are.

It could be great to emphasize this in README.

**Comment by cnuernber** [comment]
That hits on probably the hardest aspect of this library.  It is slightly different in ways that give it some more interesting long term possibilities but create traps, similar to laziness and holding onto head and all of that.

**Comment by genmeblog** [comment]
I believe that clear information that underlying datastructures are lazy and non-caching + implications of that approach with benefits like: low memory footprint, oparations are declaration of computation, separation of declaration and evaluation (computation), and traps like: full reevaluation during realization of data and manual control of snapshoting (as I perceive `clone`) could be enough. But it should be stated in `dataset` library level, not `datatype`. Maybe let's move this discussion to Zulip for wider audience.

**Comment by cnuernber** [comment]
Closing this for now.  Nothing obvious to fix.

**Comment by ezmiller** [comment]
@cnuernber has the behavior here been fixed/changed? When I ran @genmeblog 's example from the top it didn't seem to execute the function each time...

```
(def DS (ds/->dataset {:a [1 2] :b [3 4]}))

(def counter (atom 0))

(defn inc-with-counter
  [v]
  (swap! counter inc)
  (inc v))

(def processed
  (ds/column-map DS :result inc-with-counter [:a]))


processed
;; => _unnamed [2 3]:
;;    | :a | :b | :result |
;;    |---:|---:|--------:|
;;    |  1 |  3 |       2 |
;;    |  2 |  4 |       3 |

@counter
;; => 2

processed
;; => _unnamed [2 3]:
;;    | :a | :b | :result |
;;    |---:|---:|--------:|
;;    |  1 |  3 |       2 |
;;    |  2 |  4 |       3 |

@counter
;; => 2

```

**Comment by cnuernber** [comment]
Right - the column-map operation is no longer lazy - so this issue I guess is fixed.
