### ISSUE TITLE
Printing numbers

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#87]
This is caught by Daniel. Printing numbers result with different sizes as strings.

```clojure
(ds/name-values-seq->dataset {:a [0.000001 0.00001 0.0001 0.001 0.01 0.1
                                  1.0 10.0 100.0 1000.0 10000.0 100000.0]})
;; => _unnamed [12 1]:
;;    |        :a |
;;    |-----------|
;;    | 1.000E-06 |
;;    | 1.000E-05 |
;;    | 0.0001000 |
;;    |  0.001000 |
;;    |   0.01000 |
;;    |    0.1000 |
;;    |     1.000 |
;;    |     10.00 |
;;    |     100.0 |
;;    |      1000 |
;;    | 1.000E+04 |
;;    | 1.000E+05 |

(ds/name-values-seq->dataset {:a [10.0 10.1 10.11 10.111 10.1111 10.11111
                                  1.0 1.1 1.11 1.111 1.1111 1.11111
                                  0.0 0.1 0.11 0.111 0.1111 0.11111]})
;; => _unnamed [18 1]:
;;    |     :a |
;;    |--------|
;;    |  10.00 |
;;    |  10.10 |
;;    |  10.11 |
;;    |  10.11 |
;;    |  10.11 |
;;    |  10.11 |
;;    |  1.000 |
;;    |  1.100 |
;;    |  1.110 |
;;    |  1.111 |
;;    |  1.111 |
;;    |  1.111 |
;;    |  0.000 |
;;    | 0.1000 |
;;    | 0.1100 |
;;    | 0.1110 |
;;    | 0.1111 |
;;    | 0.1111 |
```

This how R does:

```r
> a<-data.table(a=c(0.000001,0.00001,0.0001,0.001,0.01,0.1,1.0,10.0,100.0,1000.0,10000.0,100000.0))
> a
        a
 1: 1e-06
 2: 1e-05
 3: 1e-04
 4: 1e-03
 5: 1e-02
 6: 1e-01
 7: 1e+00
 8: 1e+01
 9: 1e+02
10: 1e+03
11: 1e+04
12: 1e+05
> b<-data.table(a=c(10.0,10.1,10.11,10.111,10.1111,10.11111,1.0,1.1,1.11,1.111,1.1111,1.11111,0.0,0.1,0.11,0.111,0.1111,0.11111))
> b
           a
 1: 10.00000
 2: 10.10000
 3: 10.11000
 4: 10.11100
 5: 10.11110
 6: 10.11111
 7:  1.00000
 8:  1.10000
 9:  1.11000
10:  1.11100
11:  1.11110
12:  1.11111
13:  0.00000
14:  0.10000
15:  0.11000
16:  0.11100
17:  0.11110
18:  0.11111
```

**Comment by cnuernber** [comment]
This is a bit tougher.  I agree R looks really nice; right now we always print with 4 significant digits which doesn't take the rest of the data in the column into account.  To pre-scan each numeric column in order to find the ideal print argument would be a solid improvement but I don't know if I am up for that right now.

**Comment by genmeblog** [comment]
It can be left for later. Prescanning is perfectly ok while you print 25 rows currently.

If I find some nice algorithm I post it here.

**Comment by cnuernber** [comment]
Yes, please do.  The R source code probably has the best algorithm :-).

**Comment by genmeblog** [comment]
I haven't found good algorithm yet but maybe something simplified?

If numbers is less then 1e-6 or higher than 1e6 - use scientific notation.
Otherwise fix precision to 5 (or 4 or 6) numbers. It would be better than current way.

See below example, only integer part is printed.

```clojure
(def data (ds/name-values-seq->dataset {:id (range 1950.0 1960.0 (/ 1 12))}))

data
;; => _unnamed [121 1]:
;;    |  :id |
;;    |------|
;;    | 1950 |
;;    | 1950 |
;;    | 1950 |
;;    | 1950 |
;;    | 1950 |
;;    | 1950 |
;;    | 1951 |
;;    | 1951 |
;;    | 1951 |
;;    | 1951 |
;;    | 1951 |
;;    | 1951 |
;;    | 1951 |
;;    | 1951 |
;;    | 1951 |
;;    | 1951 |
;;    | 1951 |
;;    | 1951 |
;;    | 1952 |
;;    | 1952 |
;;    | 1952 |
;;    | 1952 |
;;    | 1952 |
;;    | 1952 |
;;    | 1952 |

(data :id)
;; => #tech.ml.dataset.column<float64>[121]
;;    :id
;;    [1950, 1950, 1950, 1950, 1950, 1950, 1951, 1951, 1951, 1951, 1951, 1951, 1951, 1951, 1951, 1951, 1951, 1951, 1952, 1952, ...]
```

**Comment by cnuernber** [comment]
Well, true but if we chose 5 significant figures then I could come up with an example that would fail.  In your example it is printing 4 significant figures every time, just the example is setup such that the interesting bit is the 5th one.

**Comment by genmeblog** [comment]
Yes, you're right, arbitrary precision is still wrong choice here.

**Comment by genmeblog** [comment]
Hi! As you adviced I checked what is done in R. Oh man... Anyway I simplified it as much as I could and looks like I have a working version.

https://gist.github.com/genmeblog/3f12c557cfe082d11f4ed25ee5ef3b07

You can freely copy and reuse this code.

There are two public functions:

* `formatter` - returns string formatter
* `format-sequence` - to perform formatting on string of doubles

Arguments:

* `xs` - seq of doubles
* `digits` - maximum precision on the right side (default: 8).
* `threshold` - when (what power) to switch to scientific notation, (default: 8, means numbers outside `10^-8` and `10^8` range return scientific notation string).

I would prepare PR but I have no idea how to integrate it well. I, of course, will maintain this piece of code in case of bugs.

**Comment by genmeblog** [comment]
Additionally for numbers I would align them to the right position. It's done via header separator with colon near right bar.

Aligned:

```
| header  |
|--------:|
| 3.234   |
| 222.330 |
```

| header  |
|--------:|
| 3.234   |
| 222.330 |

Normal:

```
| header  |
|---------|
| 3.234   |
| 222.330 |
```

| header  |
|---------|
| 3.234   |
| 222.330 |

**Comment by genmeblog** [comment]
Maybe I should make a small library with this formatter?

**Comment by genmeblog** [comment]
Just updated gist. `nil`, `##NaN`, `##Inf` and `##-Inf` are added now.

**Comment by cnuernber** [comment]
I integrated the formatter and will do a point release.  I think it is better in general but has some regressions.  For instance, printing stocks used to look like:
```console

tech.ml.dataset.print> (ds/head (ds/->dataset "test/data/stocks.csv"))
test/data/stocks.csv [5 3]:

| symbol |       date | price |
|--------|------------|------:|
|   MSFT | 2000-01-01 | 39.81 |
|   MSFT | 2000-02-01 | 36.35 |
|   MSFT | 2000-03-01 | 43.22 |
|   MSFT | 2000-04-01 | 28.37 |
|   MSFT | 2000-05-01 | 25.45 |
```

And it now looks like:
```console

tech.ml.dataset.print> (ds/head (ds/->dataset "test/data/stocks.csv"))
test/data/stocks.csv [5 3]:

| symbol |       date |       price |
|--------|------------|------------:|
|   MSFT | 2000-01-01 | 39.81000000 |
|   MSFT | 2000-02-01 | 36.35000000 |
|   MSFT | 2000-03-01 | 43.22000000 |
|   MSFT | 2000-04-01 | 28.37000000 |
|   MSFT | 2000-05-01 | 25.45000000 |
```

Somehow we need to detect significant digits and the set the digits member going into that function.

**Comment by genmeblog** [comment]
Ok, indeed. I can confirm it. Checking.

**Comment by genmeblog** [comment]
Well... Never faced this problem, `float` -> `double` creates the issue here...

```clojure
(first ((ds/head ds) "price"))
;; => 39.81

(class (first ((ds/head ds) "price")))
;; => java.lang.Float

(double (first ((ds/head ds) "price")))
;; => 39.810001373291016

(float 39.81)
;; => 39.81

(double (float 39.81))
;; => 39.810001373291016
```

**Comment by genmeblog** [comment]
Gist updated. Looks like this is the only way to deal with Floats:

https://gist.github.com/genmeblog/3f12c557cfe082d11f4ed25ee5ef3b07#file-format_sequence-clj-L72

There was also another bug, here:

https://gist.github.com/genmeblog/3f12c557cfe082d11f4ed25ee5ef3b07#file-format_sequence-clj-L46

**Comment by cnuernber** [comment]
Got it.  The tests pass, the numbers look great.
`2.01` is up :-).
