### ISSUE TITLE
def item from column fails

### ISSUE THREAD

**Issue by alex314159** [techascent/tech.ml.dataset#91]
Thanks for the great work - I'm in the process of migrating a Python app and it's been very helpful.

I find this behaviour odd:

`(def my-table (ds/->dataset [{:a 1 :b 2} {:a 3 :b 5}]))`
`(def my-column (my-table :b))`
`(my-column 1) ;this is fine`
`=> 5 ` 

`(def x (my-column 1))`
Execution error (AbstractMethodError) at tech.ml.dataset.impl.column.Column/applyTo (column.clj:-1).
Method tech/ml/dataset/impl/column/Column.applyTo(Lclojure/lang/ISeq;)Ljava/lang/Object; is abstract

What is the correct way of finding an index in a column? It's also odd because in a `let` binding it seems to work. Thank you,

**Comment by cnuernber** [comment]
Huh, that is odd.  Potentially in a let binding it is using clojure.lang.Indexed for destructuring.  In any case what you have above should work but be fairly inefficient.  

Readers support random access, columns are guaranteed to have a conversion to a reader but are not themselves readers.  so `(def my-column (dtype/->reader (my-table :b)))` would behave the way you want it to (and be efficient).

**Comment by alex314159** [comment]
Thanks for the quick reply and the tip re readers. I can see that using `nth` on a reader column works well for me. 

Note that inherently the reader still has the same weird behaviour:
`((dtype/->reader (my-table :b)) 1)`
`=> 5`

`(def x ((dtype/->reader (my-table :b)) 1))`
Execution error (AbstractMethodError) at tech.v2.datatype.reader$fn$reify__13502/applyTo (reader.clj:-1).
Method tech/v2/datatype/reader$fn$reify__13502.applyTo(Lclojure/lang/ISeq;)Ljava/lang/Object; is abstract

**Comment by cnuernber** [comment]
Well, thanks for the issue.  Both of these cases should work just with the column case being somewhat inefficient so I will address this in code soon.

**Comment by cnuernber** [comment]
Both paths should work now.

**Comment by alex314159** [comment]
that's great! thank you
