### ISSUE TITLE
name-values-seq path in ->dataset

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#92]
`->dataset` called with a map fails. The path calls `name-values-seq` here:

https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/ml/dataset/base.clj#L832

Two solutions:
- add `apply`
- or switch to `parse-nvs`

**Comment by cnuernber** [comment]
Yep, sorry, thanks for the heads up.
