### ISSUE TITLE
What about loading smile supported datasets via ->dataset?

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#93]
Current implementation require Smile dataframe object. But I think they can be transparently loaded with `->dataset`.  It looks trivial when based on file extension and `smile.io`.

**Comment by cnuernber** [comment]
I thought this request would come through :-).  As long as they are identifiable via file extension it should be straight forward.

**Comment by cnuernber** [comment]
Sort of works.  The iris dataset fails during load so I need a valid arrow file.  But anything with the .feather file extension will cause the arrow loading scheme to fire.  

It will be up to the user to include the required dependencies.  Will document somewhere.
