### ISSUE TITLE
Have clear example for custom string-row-based CSV parsing steps

### ISSUE THREAD

**Issue by cnuernber** [techascent/tech.ml.dataset#95]
There are often times when you can do filtering or sampling or adjustments to data while it is in string-array-row format.  This can dramatically decrease the work the parsing engine has to do later.  It would be useful to have an example of working in this space as there is actually quite a lot you can do and it enables in some cases extremely large datasets to be loaded.

**Comment by harold** [comment]
Nice. I think this is perhaps especially interesting when done in such a way that not all rows need to be in memory at once. For instance, load this tsv, but remove any rows with an `X` in column 7, and then make a dataset out of the rest. It'd be neat if this could be done in a way where you never really use much more memory than just the rows without an `X` in column 7 would take.

**Comment by cnuernber** [comment]
https://github.com/techascent/tech.ml.dataset/blob/master/docs/csv-space-operations.md

**Comment by harold** [comment]
👍
